## Basic Level (1-20)

#### **1. What is NumPy and why is it used?**
**NumPy (Numerical Python)** is the foundational library for scientific and numerical computing in Python. It introduces a highly efficient, multi-dimensional array object called `ndarray` and provides a vast collection of mathematical functions to operate on these arrays.

* **Blazing Fast Performance (Vectorization):** Under the hood, NumPy is written in C. It uses **vectorization** to apply operations to entire arrays at once, entirely bypassing Python's slow `for` loops and interpreter overhead.

* **Contiguous Memory Allocation:** Unlike standard Python lists, which are basically arrays of memory pointers pointing to scattered objects, NumPy arrays store elements of the same data type (`dtype`) in single, continuous blocks of memory. This makes fetching and processing data exponentially faster.

* **Broadcasting:** NumPy features a powerful mathematical engine that automatically handles operations between arrays of different shapes and sizes without needing to replicate data in memory.

* **The Ecosystem Foundation:** Almost every major data science and machine learning library in Python (Pandas, SciPy, Scikit-learn, TensorFlow) relies on NumPy arrays as their underlying data structure.

In [12]:
# Importing NumPy Library in Python
import numpy as np

#### **2. What is an ndarray?**
An **`ndarray` (N-dimensional array)** is the central data structure of the NumPy library. It is a fast, flexible container designed to hold large datasets and perform mathematical operations on them efficiently.

**Key Characteristics of an ndarray:**
* **Homogeneous Data:** Every element inside an `ndarray` must be of the exact same data type (e.g., all 32-bit integers, or all 64-bit floats). Because the data type is uniform, NumPy doesn't have to waste time checking the type of every single element before operating on it.

* **Fixed Size:** Unlike standard Python lists which can grow or shrink dynamically, an `ndarray` has a fixed size created at initialization. If you need to change its size (like appending elements), NumPy typically creates a brand new array under the hood.

* **Strided Memory:** Data is stored in a continuous block of memory. The `ndarray` object acts as a "view" that tells Python exactly how to interpret that raw memory (using "strides") to read it as a 1D vector, 2D matrix, or multi-dimensional tensor.

**Must-Know Attributes for Interviews:**
If an interviewer asks how you would inspect a mysterious dataset loaded into a NumPy array, you should immediately mention checking these attributes:

* **`.ndim`**: Returns the number of dimensions (axes).
* **`.shape`**: Returns a tuple showing the size of the array across each dimension (e.g., `(100, 5)` for 100 rows and 5 columns).
* **`.size`**: Returns the total number of elements in the entire array.
* **`.dtype`**: Returns the specific data type of the array's elements (e.g., `float64`, `int32`).

In [13]:
import numpy as np

# Creating an ndarray from a nested Python list (2D Matrix)
data = [[1, 2, 3], 
        [4, 5, 6]]
arr_2d = np.array(data)

print("Target Array:\n", arr_2d)
print("-" * 30)

# Inspecting the crucial attributes (The "Diagnostic Check")
print("Object Type:  ", type(arr_2d))       # <class 'numpy.ndarray'>
print("Dimensions:   ", arr_2d.ndim)        # 2 (since it's a matrix)
print("Shape:        ", arr_2d.shape)       # (2, 3) -> 2 rows, 3 columns
print("Total Size:   ", arr_2d.size)        # 6 elements total
print("Data Type:    ", arr_2d.dtype)       # int32 or int64
print("-" * 30)

# Allocate uninitialized memory
a = np.ndarray(shape=(3, 4)) 
# Overwrite everything using slice assignment [:]
a[:] = [
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]]

print("Using ndarray:\n", a)

Target Array:
 [[1 2 3]
 [4 5 6]]
------------------------------
Object Type:   <class 'numpy.ndarray'>
Dimensions:    2
Shape:         (2, 3)
Total Size:    6
Data Type:     int64
------------------------------
Using ndarray:
 [[ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [ 90. 100. 110. 120.]]


#### **3. Difference between Python list and NumPy array?**
This is one of the most guaranteed questions in any Python data science interview. Interviewers are looking for you to mention **memory layout**, **homogeneity**, and **vectorization**.

**The Quick Comparison Table**  
| Feature | Python `list` | NumPy `ndarray` |
| --- | --- | --- |
| **Data Types** | **Heterogeneous:** Can mix integers, strings, objects, etc. | **Homogeneous:** All elements must be the exact same data type (`dtype`). |
| **Memory Layout** | **Scattered:** Stores an array of *pointers* to objects scattered across memory. | **Contiguous:** Stores actual data in a single, continuous block of memory. |
| **Performance** | **Slow:** Python must check the type of every single element during iterations. | **Fast:** Uses C-based vectorization; skips element-level type checking. |
| **Math Operations** | **Concatenation:** `+` joins lists together. `*` repeats the list. | **Element-wise:** `+`, `-`, `*` apply the math operation to the actual numbers. |
| **Size** | **Dynamic:** Can easily grow or shrink using `.append()` or `.remove()`. | **Fixed:** Size is locked at creation. Appending usually means creating a brand new array. |

**What to emphasize out loud:**  
*"Because NumPy arrays are strictly typed and contiguous in memory, they can push operations down to highly optimized C-code rather than relying on Python's slow loops. This is called **vectorization**."*

In [14]:
# If an interviewer asks you to demonstrate the difference on a whiteboard or in a live coding pad, 
# show them how the + and * operator behaves differently

import numpy as np
# Python List Behavior
list_a = [1, 2, 3]
list_b = [4, 5, 6]
print("List addition: ", list_a + list_b)
print("List multiplication: ", 2*list_a)  
# Output: [1, 2, 3, 4, 5, 6] (Concatenation)

# NumPy Array Behavior
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
print("Array addition:", arr_a + arr_b)    
print("Array multiplication:", 2*arr_a)    
# Output: [5 7 9] (Element-wise math / Vectorization)

List addition:  [1, 2, 3, 4, 5, 6]
List multiplication:  [1, 2, 3, 1, 2, 3]
Array addition: [5 7 9]
Array multiplication: [2 4 6]


In [15]:
%time np.array([1, 2, 3, 4])
%time list([1, 2, 3, 4])

%time np.array([1.0, 2.0, 3.0, 4.0])
%time list([1.0, 2.0, 3.0, 4.0])

%time np.array([1.0/2, 2.0/2, 3.0/2, 4.0/2])
%time list([1.0/2, 2.0/2, 3.0/2, 4.0/2])

CPU times: user 8 μs, sys: 0 ns, total: 8 μs
Wall time: 10 μs
CPU times: user 2 μs, sys: 1e+03 ns, total: 3 μs
Wall time: 3.1 μs
CPU times: user 4 μs, sys: 0 ns, total: 4 μs
Wall time: 6.2 μs
CPU times: user 1e+03 ns, sys: 1 μs, total: 2 μs
Wall time: 1.91 μs
CPU times: user 2 μs, sys: 0 ns, total: 2 μs
Wall time: 4.05 μs
CPU times: user 1e+03 ns, sys: 0 ns, total: 1e+03 ns
Wall time: 1.67 μs


[0.5, 1.0, 1.5, 2.0]

In [16]:
%time print(np.array([1, 2.5, "Data Science", {1: "toy", 2: "ball"}]))
%time print(list([1, 2.5, "Data Science", {1: "toy", 2: "ball"}]))

[1 2.5 'Data Science' {1: 'toy', 2: 'ball'}]
CPU times: user 83 μs, sys: 15 μs, total: 98 μs
Wall time: 98.2 μs
[1, 2.5, 'Data Science', {1: 'toy', 2: 'ball'}]
CPU times: user 13 μs, sys: 0 ns, total: 13 μs
Wall time: 15.3 μs


#### **4. How do you create a NumPy array?**
For an interview cheat sheet, it is best to categorize array creation methods by their use case. Interviewers often test if you know the most efficient built-in function rather than manually writing loops.

**1. From Existing Data (Lists/Tuples)**  
Use `np.array()` when you already have Python data structures.
* **`np.array(list)`**: Converts a list (or nested list) into a 1D or multi-dimensional array.

**2. Pre-filled Arrays (Shape-Based)**  
Used when you need to allocate an array of a specific shape quickly. You pass a tuple representing the shape, like `(rows, columns)`.
* **`np.zeros(shape)`**: Fills the array with `0.0`. Great for initializing weights in neural networks.
* **`np.ones(shape)`**: Fills the array with `1.0`.
* **`np.full(shape, fill_value)`**: Fills the array with a specific number.

**3. Numerical Sequences**  
Used to generate ranges of numbers automatically.
* **`np.arange(start, stop, step)`**: Works like Python's built-in `range()`, but returns an array. The `stop` value is exclusive.
* **`np.linspace(start, stop, num)`**: Generates exactly `num` evenly spaced points between `start` and `stop` (inclusive). **Interview tip:** Use this when you care about the *exact number of elements* rather than the step size.

**4. Random Data Generation**  
Crucial for creating mock datasets or initializing randomized models.
* **`np.random.rand(d0, d1...)`**: Uniform distribution between 0 and 1.
* **`np.random.randint(low, high, size)`**: Random integers.

In [38]:
import numpy as np

# 1. From existing data
list_data = [10, 20, 30]
arr_from_list = np.array(list_data)
print("arr_from_list: ", arr_from_list)

# 2. Pre-filled arrays (pass a shape tuple)
zeros_matrix = np.zeros((2, 3))       # 2x3 matrix of zeros
full_matrix = np.full((2, 2), 99)     # 2x2 matrix filled with 99
print("full_matrix:\n", full_matrix)
print("zeros_matrix:\n", zeros_matrix)

# 3. Numerical sequences
range_arr = np.arange(0, 10, 2)       # [0, 2, 4, 6, 8]
linear_arr = np.linspace(0, 1, 5)     # [0. , 0.25, 0.5 , 0.75, 1. ]

# 4. Random data
random_ints = np.random.randint(1, 100, size=(3, 3)) # 3x3 matrix of random ints 1-99

print("np.arange output:  ", range_arr)
print("np.linspace output:", linear_arr)
print("Random matrix:\n", random_ints)

arr_from_list:  [10 20 30]
full_matrix:
 [[99 99]
 [99 99]]
zeros_matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]
np.arange output:   [0 2 4 6 8]
np.linspace output: [0.   0.25 0.5  0.75 1.  ]
Random matrix:
 [[61 32 65]
 [16 75 37]
 [43 56  4]]


#### **5. What is the difference between np.array() and np.asarray()?**
This is a classic "gotcha" question that tests your understanding of memory management and copying in Python. The core difference comes down to **whether or not a new copy of the object is created in memory.**

**The Short Answer**  
* **`np.array()`** will create a **copy** of the object by default (though you can change this with the `copy=False` parameter).
* **`np.asarray()`** will **avoid making a copy** whenever possible. If the input is already a NumPy array of the same data type, it simply returns a reference (a view) to the original array.

**Why does this matter for interviews? (The Use Case)**  
If you are writing a machine learning function that takes data as an input, the user might pass a Python list *or* an existing NumPy array.
* If you use `np.array(input_data)`, you might accidentally duplicate a massive 5GB dataset in RAM, crashing your program.
* If you use `np.asarray(input_data)`, lists get safely converted to arrays, but existing arrays pass through instantly without using extra memory.

In [39]:
import numpy as np

# 1. Create an original NumPy array
original = np.array([1, 2, 3])

# 2. Pass it through both functions
arr_copy = np.array(original)
arr_view = np.asarray(original)

# 3. Modify the original array
original[0] = 99

print("Original array: ", original)
# Output: [99, 2, 3]

print("np.array():     ", arr_copy) 
# Output: [1, 2, 3] -> (Unaffected! It made a completely new copy in memory)

print("np.asarray():   ", arr_view) 
# Output: [99, 2, 3] -> (Affected! It just pointed to the original memory block)

Original array:  [99  2  3]
np.array():      [1 2 3]
np.asarray():    [99  2  3]


#### **6. How do you check the shape of an array?**
To check the shape of a NumPy array, you use the **`.shape`** attribute. It returns a tuple of integers representing the number of elements along each dimension (axis) of the array.

**What the interviewer is looking for:**  
They want to ensure you know that `.shape` is an **attribute** (a property of the object), not a method. You should never use parentheses when calling it.
* **Correct:** `arr.shape`
* **Incorrect (will throw an error):** `arr.shape()`

**How to read the shape tuple:**  
* **1D Array (Vector):** `(n,)` where `n` is the number of elements. *Note the trailing comma, which confirms it is a 1D tuple.*
* **2D Array (Matrix):** `(rows, columns)`. For example, `(3, 4)` means 3 rows and 4 columns.
* **3D Array (Tensor):** `(depth, rows, columns)` or `(matrices, rows, columns)`.

In [40]:
import numpy as np

# 1D Array
arr_1d = np.array([10, 20, 30, 40])
print("1D Array shape:", arr_1d.shape)  
# Output: (4,) -> 4 elements in a single dimension

# 2D Matrix
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("2D Matrix shape:", arr_2d.shape) 
# Output: (2, 3) -> 2 rows, 3 columns

# 3D Tensor (e.g., 2 color images, 3 pixels tall, 3 pixels wide)
arr_3d = np.zeros((2, 3, 3))
print("3D Tensor shape:", arr_3d.shape) 
# Output: (2, 3, 3)

1D Array shape: (4,)
2D Matrix shape: (2, 3)
3D Tensor shape: (2, 3, 3)


#### **7. How do you check the datatype of elements?**
To check the datatype of the elements inside a NumPy array, you use the **`.dtype`** attribute.

**What the interviewer is looking for:**  
Interviewers want to see that you understand the difference between inspecting the array object itself versus inspecting the contents of the array.
* **`type(arr)`**: This is a built-in Python function. It will always return `<class 'numpy.ndarray'>` because that is the container's object type.
* **`arr.dtype`**: This is a NumPy attribute. It returns the actual data type of the uniform elements stored *inside* the container (e.g., `int32`, `float64`, `bool`).

**Common Data Types in NumPy**  
* **Integers:** `int8`, `int16`, `int32`, `int64`
* **Floats:** `float16`, `float32`, `float64`
* **Booleans:** `bool_`
* **Strings/Objects:** `object`, `string_`

In [41]:
import numpy as np

# Create an array of integers
arr_int = np.array([1, 2, 3])

# Create an array of floats
arr_float = np.array([1.5, 2.5, 3.5])

# The Interview "Gotcha"
print("Object type:  ", type(arr_int))   # Output: <class 'numpy.ndarray'>
print("Element type: ", arr_int.dtype)   # Output: int32 (or int64 depending on OS)

# Inspecting the float array
print("Float array element type:", arr_float.dtype) # Output: float64

Object type:   <class 'numpy.ndarray'>
Element type:  int64
Float array element type: float64


#### **8. What is dtype in NumPy?**
In NumPy, **`dtype` (data type object)** is an object that describes how the raw bytes in an array's memory block should be interpreted.

While standard Python only has basic types like `int` or `float`, NumPy provides a much finer level of control over data, which is essential for performance and memory management in data science.

**Why `dtype` matters in an interview context:**  
Interviewers want to see that you understand the underlying mechanics of NumPy's speed.
* **The Secret to C-Level Speed:** A standard Python list contains memory pointers pointing to heavy Python objects scattered across RAM. A NumPy array contains a single block of raw bytes. The `dtype` simply tells NumPy, *"Read every 4 bytes in this block as a 32-bit integer."* This allows NumPy to process the data at hardware speeds.
* **Memory Optimization:** In machine learning (like processing millions of images), using a 64-bit float (`float64`) when a 16-bit float (`float16`) would suffice wastes massive amounts of RAM. `dtype` gives you the power to optimize this.

**Common NumPy dtypes:**  
* `int8`, `int16`, `int32`, `int64` (Signed integers)
* `uint8`, `uint16`, `uint32`, `uint64` (Unsigned integers - no negative numbers, often used for image pixels)
* `float16`, `float32`, `float64` (Floating-point numbers)
* `bool_` (Booleans)

In [45]:
# You can explicitly set the `dtype` when you create an array to force NumPy to use a specific memory footprint.
import numpy as np

# 1. Let NumPy infer the dtype (Defaults to int32 or int64)
auto_arr = np.array([1, 2, 3])
print("Inferred dtype: ", auto_arr.dtype)

# 2. Explicitly force a memory-efficient dtype (8-bit integer)
# This uses 4x to 8x less memory than the default!
tiny_arr = np.array([1, 2, 3], dtype=np.int8)
print("Forced dtype:   ", tiny_arr.dtype)

# 3. Force strings to be interpreted as floats
float_arr = np.array(['1.5', '2.6', '3.7'], dtype=np.float32)
print("String to float:", float_arr)

# 4. Force floats to be interpreted as ints
int_arr = np.array([1.5, 2.6, 3.7], dtype=np.int8)
print("Float to int:", int_arr)

Inferred dtype:  int64
Forced dtype:    int8
String to float: [1.5 2.6 3.7]
Float to int: [1 2 3]


#### **9. How to create Zeros array, Ones array, Identity matrix?**

These are fundamental initialization functions in NumPy. Interviewers expect you to know these by heart, as they are constantly used to initialize weights in machine learning models, create masks, or set up linear algebra operations.

**1. Zeros Array: `np.zeros(shape)`**  
Creates an array filled entirely with zeros. You must pass the desired dimensions as a tuple (unless it is just a 1D array, then a single integer works).
* **Default `dtype`:** `float64`. (Interviewers often ask this! Zeros are floats by default, not integers).

**2. Ones Array: `np.ones(shape)`**  
Creates an array filled entirely with ones. Like `np.zeros`, it takes a shape tuple.
* **Pro-tip:** If you need an array filled with 7s, you can do `np.ones(shape) * 7`, though `np.full(shape, 7)` is slightly more efficient.

**3. Identity Matrix: `np.eye(N)` or `np.identity(N)`**  
An identity matrix is a fundamental concept in linear algebra: a square 2D matrix with `1`s on the main diagonal and `0`s everywhere else.
* **`np.eye(N)`:** The most common function. You pass a single integer `N` to create an `N x N` matrix. It is flexible and even allows you to offset the diagonal using the `k` parameter.
* **`np.identity(N)`:** A stricter function that only ever creates square matrices. `np.eye` is generally preferred.

In [46]:
import numpy as np

# 1. Zeros Array
# Pass a single int for 1D, or a tuple for 2D+
zeros_1d = np.zeros(5)
zeros_2d = np.zeros((3, 4)) 
print("Zeros Matrix (3x4):\n", zeros_2d)
print("-" * 20)

# 2. Ones Array
ones_2d = np.ones((2, 2))
print("Ones Matrix (2x2):\n", ones_2d)
print("-" * 20)

# 3. Identity Matrix
# Pass a single integer N to create an N x N square matrix
identity_3x3 = np.eye(3)
print("Identity Matrix (3x3):\n", identity_3x3)

Zeros Matrix (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
--------------------
Ones Matrix (2x2):
 [[1. 1.]
 [1. 1.]]
--------------------
Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### **10. What is the difference between np.arange() and np.linspace()?**
This is a very common interview question. While both functions generate 1D arrays of evenly spaced numbers, they approach the problem from completely different angles.

The short answer is: **`arange` cares about the *step size*, while `linspace` cares about the *number of elements*.**

**The Comparison**  
| Feature | `np.arange(start, stop, step)` | `np.linspace(start, stop, num)` |
| --- | --- | --- |
| **Primary Argument** | The **step size** between each number. | The total **number of points** you want. |
| **Endpoint (stop)** | **Exclusive:** The array stops *before* reaching the stop value. | **Inclusive:** The array includes the stop value (by default). |
| **Best Use Case** | When you know exactly how far apart each number should be (e.g., "count by 2s"). | When you need exactly `N` data points between two boundaries (e.g., graph axes). |
| **Float Handling** | **Dangerous:** Using float steps (like `0.1`) can cause unexpected results due to floating-point precision issues. | **Safe:** Perfectly handles float boundaries and evenly calculates the distance between them. |

**The Interview "Gotcha" (Floating Point Precision)**  
If an interviewer asks, *"How would you create an array of numbers from 0 to 1, stepping by 0.1?"*, you should explain why `linspace` is safer than `arange`.

Because computers struggle to represent fractions like `0.1` perfectly in binary, `np.arange(0, 1, 0.1)` can sometimes include or exclude the final number unpredictably depending on the exact machine architecture. `np.linspace(0, 1, 11)` guarantees exactly 11 points, perfectly spaced.

In [47]:
import numpy as np

# 1. np.arange: "Start at 0, stop BEFORE 10, step by 2"
# We care about the size of the jump.
arange_arr = np.arange(0, 10, 2)
print("arange output:   ", arange_arr) 
# Output: [0, 2, 4, 6, 8] (Notice 10 is excluded)

# 2. np.linspace: "Start at 0, stop AT 10, give me exactly 5 numbers"
# We care about the total number of elements.
linspace_arr = np.linspace(0, 10, 5)
print("linspace output: ", linspace_arr) 
# Output: [ 0.   2.5  5.   7.5 10. ] (Notice 10 is included)

arange output:    [0 2 4 6 8]
linspace output:  [ 0.   2.5  5.   7.5 10. ]


#### **11. How do you reshape an array?**
To reshape a NumPy array, you use the **`.reshape(shape)`** method. This allows you to change the dimensions (like turning a 1D vector into a 2D matrix) without changing the underlying data.

A visual representation of converting a 1D array of 4 elements into a 2x2 matrix:

![Reshape](reshape.png)

**The Golden Rule of Reshaping**  
The total number of elements must remain exactly the same. For example, if you have a 1D array with 12 elements, you can reshape it into `(3, 4)`, `(4, 3)`, or `(2, 6)` because the math multiplies out to 12. If you try to reshape it to `(3, 5)`, NumPy will throw a `ValueError`.

**The `-1` Trick (Interview Must-Know)**  
Interviewers love to test if you know how to use `-1` in reshape.

If you know you want a specific number of columns, but you don't want to calculate how many rows are needed, you can pass `-1` for the unknown dimension. NumPy will automatically calculate the correct size based on the length of the array. This is especially useful in machine learning when you need to convert an unknown number of samples into a single column vector using `.reshape(-1, 1)`.

In [51]:
import numpy as np

# Create a 1D array with 12 elements
arr_1d = np.arange(1, 13) 
print("Original 1D:", arr_1d)

# 1. Standard Reshape to 3 rows, 4 columns
arr_2d = arr_1d.reshape((3, 4))
print("Reshaped to 3x4:\n", arr_2d)

# 2. Reshape to 3D Tensor (2 matrices, 2 rows, 3 columns)
arr_3d = arr_1d.reshape((2, 2, 3))
print("Reshaped to 2x2x3:\n", arr_3d)

# 3. The -1 Trick: "Give me exactly 1 column, calculate the rows automatically"
column_vector = arr_1d.reshape(-1, 1)
print("Column Vector shape:", column_vector.shape) # Output: (12, 1)

# 4. The -1 Trick: "Give me 4 columns, calculate the rows automatically"
auto_rows = arr_1d.reshape(-1, 4)
print("Auto-calculated rows shape:", auto_rows.shape) # Output: (3, 4)

Original 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped to 2x2x3:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Column Vector shape: (12, 1)
Auto-calculated rows shape: (3, 4)


#### **12. What is the difference between reshape() and resize()?**
This is a subtle but critical question that tests your understanding of **in-place operations** and **memory mutability** in Python.

The short answer is: **`reshape()` returns a new view without modifying the original array, while the `.resize()` method modifies the original array in-place.**

**The Quick Comparison Table**  
| Feature | `arr.reshape(shape)` | `arr.resize(shape)` |
| --- | --- | --- |
| **Original Array** | Remains unchanged (Returns a new view). | **Modified in-place** (The original object changes). |
| **Element Count** | Must match exactly (e.g., 4 elements to 2x2). | Must match exactly if using the object method. |
| **Return Value** | Returns the newly shaped array. | Returns `None` (because it modifies the original). |

**The "Bonus Points" Detail: `arr.resize()` vs `np.resize()`**  
If you want to really impress the interviewer, mention that NumPy actually has *two* resize functions with very different behaviors:

1. **`arr.resize(shape)` (The Method):** Modifies the array in-place. It will throw an error if you try to change the total number of elements.
2. **`np.resize(arr, shape)` (The Function):** Returns a *new* array. Unlike reshape, **it allows you to change the total number of elements**. If the new shape is larger, it repeats the data to fill the space. If it is smaller, it truncates the data.

In [50]:
import numpy as np

# 1. Reshape: Original is safe 
arr_1 = np.array([1, 2, 3, 4])
reshaped_arr = arr_1.reshape((2, 2))
print("Original after reshape:\n", arr_1)      # Still 1D!
print("Reshaped output:\n", reshaped_arr)
print("-" * 30)

# 2. Resize (Method): In-place mutation 
arr_2 = np.array([1, 2, 3, 4])
arr_2.resize((2, 2))  # Returns None!
print("Original after resize:\n", arr_2)       # Now it's 2D!
print("-" * 30)

# 3. Resize (Function): Changing element counts 
arr_3 = np.array([1, 2, 3])
# Forcing 3 elements into a 6-element shape
expanded_arr = np.resize(arr_3, (2, 3)) 
print("Expanded with np.resize:\n", expanded_arr)
# Output repeats the data: [[1, 2, 3], [1, 2, 3]]

Original after reshape:
 [1 2 3 4]
Reshaped output:
 [[1 2]
 [3 4]]
------------------------------
Original after resize:
 [[1 2]
 [3 4]]
------------------------------
Expanded with np.resize:
 [[1 2 3]
 [1 2 3]]


In [26]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a, a.shape)
print(a.reshape(4, 3))

print(np.resize(a, (11, 2)))    # growing or shrinking the array

a.resize((4, 6))
print(a)    # it alters the original array directly

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


#### **13. What is broadcasting?**
**Broadcasting** is NumPy's "magic" mechanism that allows it to perform element-wise mathematical operations on arrays of different shapes.

Normally, if you want to add two arrays together, they must be the exact same shape. Broadcasting relaxes this rule by virtually "stretching" or copying the smaller array so that it matches the dimensions of the larger array—without actually allocating extra memory or copying data.

![Broadcasting](broadcasting.png)

**The Two Rules of Broadcasting (Interview Essential)**  
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (rightmost) dimension and works its way to the left. Two dimensions are compatible if:

1. **They are exactly equal.**
2. **One of them is `1`.** (In this case, the dimension of size `1` is stretched to match the other).

If neither of these conditions is met, NumPy throws a `ValueError`. If one array has fewer dimensions than the other, NumPy pads its shape with `1`s on the left side until the number of dimensions matches.

**The Two Rules of Broadcasting**  
To determine if two arrays can be broadcast, NumPy aligns their shape tuples **right-to-left** and compares the dimensions one by one. Two dimensions are compatible if:

1. **They are exactly equal.**
2. **One of them is `1`.** (The array with size 1 is stretched to match the other dimension).

If an array has fewer dimensions than the other, NumPy implicitly pads its shape with `1`s on the left. If the dimensions still disagree after these rules, NumPy throws a `ValueError`.

> **Key Insights**  
> **1D array across a 2D Matrix:**
> matrixBroadcasting is how NumPy handles element-wise operations on arrays of different shapes. Instead of forcing you to create redundant copies of data so that arrays match perfectly in size, NumPy virtually "stretches" the smaller array across the larger one. It requires understanding how NumPy manages memory under the hood: broadcasting doesn't actually duplicate data in memory, making it incredibly fast and memory-efficient.

In [58]:
import numpy as np

# Scalar Broadcasting (The simplest form)
arr_1d = np.array([1, 2, 3])
# The scalar '10' is broadcast to [10, 10, 10]
print("Scalar addition:", arr_1d + 10) 
# Output: [11, 12, 13]

# A 2D array of shape (3, 3)
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# A 1D array of shape (3,)
row_vector = np.array([10, 20, 30])

# Broadcasting in action: 
# The row_vector is added to EACH row of the matrix automatically.
# Shape alignment:
# matrix:      (3, 3)
# row_vector:     (3,) -> padded to (1, 3) -> stretched to (3, 3)
mat_add_vec = matrix + row_vector 

print("Vector addition:\n", mat_add_vec)
# [[11 22 33]
#  [14 25 36]
#  [17 28 39]]

print("Scalar addition to matrix:\n", matrix + 2)
# [[3  4  5]
#  [6  7  8]
#  [9 10 11]]

Scalar addition: [11 12 13]
Vector addition:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
Scalar addition to matrix:
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### **14. What is vectorization?**
**Vectorization** is the primary reason we use NumPy over standard Python lists. It refers to the process of pushing mathematical operations down into highly optimized, pre-compiled C code instead of executing them through slow Python `for` loops.

When an operation is vectorized, NumPy applies it to an entire array at once.

**Why is Vectorization so fast?**  
1. **Single Instruction, Multiple Data (SIMD):** Modern computer processors can perform the same operation on multiple data points simultaneously. NumPy is built to take advantage of this hardware capability.
2. **No Type Checking Overhead:** A standard Python loop has to check the data type of *every single element*, one by one, before doing the math. Because NumPy arrays are homogeneous (one data type), it skips this check entirely.
3. **No Interpreter Overhead:** It bypasses the Python interpreter and runs directly in C.

> **Key insight:**  
> The bigger the dataset, the bigger the difference. For arrays with millions of elements, vectorized operations can be 100x to 500x faster than traditional loops.

> **Interview Tip:**  
> If you are asked to solve a problem on a whiteboard using NumPy, **never write a `for` loop.** If you write a `for` loop while using NumPy arrays, you have defeated the entire purpose of the library. Always look for a way to express the logic using whole-array operations.

In [ ]:
import numpy as np

# Create a massive dataset
# 1000 random numbers
huge_list = %timeit list(np.random.rand(1000))
huge_array = %timeit np.array(huge_list)

19.6 μs ± 5.16 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
120 ns ± 3.4 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [66]:
%%timeit 
# --- 1. The Slow Python Way (Loops) ---
def python_loop(data):
    result = []
    for item in data:
        result.append(item * 5)
    return result
# In Jupyter, run this in a cell:
python_loop(list(np.random.rand(1000)))
# Expected: ~500ms to 1000ms+

42.4 μs ± 187 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [67]:
%%timeit 
# --- 2. The Fast NumPy Way (Vectorization) ---
def numpy_vectorized(data):
    # Notice there is no loop! The math is applied to the whole array.
    return data * 5
# In Jupyter, run this in a cell:
numpy_vectorized(np.random.rand(1000))
# Expected: ~10ms to 20ms

2.64 μs ± 6.22 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### **15. How to perform element-wise operations?**
Element-wise operations are the core of NumPy's speed and syntax. When you apply basic arithmetic operators to NumPy arrays, the operation is automatically vectorized and applied element-by-element, rather than using Python's default list behavior (which is concatenation).

**The Golden Rule of Element-Wise Math**  
To perform element-wise operations, **the arrays must be the exact same shape**, or they must be capable of being **broadcast** together.

**Element-Wise vs. Matrix Multiplication (The Interview Gotcha)**  
The most common mistake candidates make in interviews is confusing element-wise multiplication with true mathematical matrix multiplication (dot product).

* **`*` (Asterisk):** Performs *element-wise* multiplication. It multiplies position `[0,0]` in matrix A with position `[0,0]` in matrix B.
* **`@` or `np.dot()`:** Performs true *matrix multiplication* (rows of matrix A multiplied by columns of matrix B).

> **Key insight:**  
> If you use `*` on two `2x2` matrices, the result is `2x2`. If you use `@` on a `2x3` matrix and a `3x2` matrix, the result is `2x2`.

In [ ]:
import numpy as np

# Create two arrays
arr_a = np.array([10, 20, 30])
arr_b = np.array([1, 2, 3])

# --- 1. Basic Arithmetic (Element-wise) ---
print("Addition (+):      ", arr_a + arr_b)    # [11, 22, 33]
print("Subtraction (-):   ", arr_a - arr_b)    # [9, 18, 27]
print("Division (/):      ", arr_a / arr_b)    # [10.0, 10.0, 10.0]
print("Exponentiation (**):", arr_a ** arr_b)      # [10, 400, 27000]

# --- 2. The Multiplication Gotcha ---
matrix_a = np.array([[1, 2], 
                     [3, 4]])
matrix_b = np.array([[2, 0], 
                     [0, 2]])

# Element-wise multiplication
print("\nElement-wise (*):\n", matrix_a * matrix_b)
# [[2 0]
#  [0 8]]

# Matrix multiplication (Dot product)
print("\nMatrix Multiplication (@):\n", matrix_a @ matrix_b)
# [[2 4]
#  [6 8]]

Addition (+):       [11 22 33]
Subtraction (-):    [ 9 18 27]
Division (/):       [10. 10. 10.]
Exponentiation (**): [   10   400 27000]

Element-wise (*):
 [[2 0]
 [0 8]]

Matrix Multiplication (@):
 [[2 4]
 [6 8]]


#### **16. What is the difference between * and dot()?**
This is a direct continuation of the previous concept, but interviewers will often ask this exact question to see if you know the formal mathematical differences and shape requirements.

The short answer is: **`*` performs element-wise multiplication, while `np.dot()` performs true matrix multiplication.**

**The Quick Comparison Table**  
| Feature | `*` (Asterisk Operator) | `np.dot()` (or `@` Operator) |
| --- | --- | --- |
| **Mathematical Name** | Hadamard Product | Dot Product / Matrix Multiplication |
| **Operation** | Multiplies corresponding elements exactly where they sit: `A[i,j] * B[i,j]`. | Multiplies rows of the first matrix by columns of the second matrix. |
| **Shape Requirement** | Arrays must be the **exact same shape** (or broadcastable). | **Inner dimensions must match.** A `(m, n)` matrix and an `(n, p)` matrix create an `(m, p)` matrix. |
| **1D Array Behavior** | Returns a new 1D array of the multiplied elements. | Returns a **scalar** (a single number) representing the inner product of the vectors. |

**The "Bonus Points" Detail**  
In modern Python (3.5+), you can use the **`@` operator** as a shorthand for `np.dot()` when working with matrices. Interviewers love to see candidates use `@` because it makes complex linear algebra code much cleaner to read (e.g., `A @ B` instead of `np.dot(A, B)`).

In [ ]:
import numpy as np

# 1. Behavior on 1D Arrays (Vectors)
vec_a = np.array([1, 2, 3])
vec_b = np.array([4, 5, 6])

print("1D Element-wise (*): ", vec_a * vec_b)      
# Output: [4, 10, 18] (Array)

print("1D Dot Product (dot):", np.dot(vec_a, vec_b)) 
# Output: 32 (Scalar: 1*4 + 2*5 + 3*6 = 32)

print("-" * 30)

# 2. Behavior on 2D Arrays (Matrices)
mat_a = np.array([[1, 2], 
                  [3, 4]])
mat_b = np.array([[5, 6], 
                  [7, 8]])

# Element-wise: 1*5, 2*6, etc.
print("2D Element-wise (*):\n", mat_a * mat_b)
# [[ 5 12]
#  [21 32]]

# Matrix Multiplication: Row 1 * Col 1, etc.
print("\n2D Matrix Math (dot):\n", np.dot(mat_a, mat_b))
# [[19 22]
#  [43 50]]

# The modern shorthand for np.dot()
print("\nModern Shorthand (@):\n", mat_a @ mat_b)

1D Element-wise (*):  [ 4 10 18]
1D Dot Product (dot): 32
------------------------------
2D Element-wise (*):
 [[ 5 12]
 [21 32]]

2D Matrix Math (dot):
 [[19 22]
 [43 50]]

Modern Shorthand (@):
 [[19 22]
 [43 50]]


#### **17. How do you concatenate arrays?**
To combine two or more NumPy arrays, you use the concatenation and stacking functions. Interviewers want to see that you understand how to control the direction of the join using the `axis` parameter, and that you know the shortcut functions.

**The 3 Core Concatenation Functions**  
1. **`np.concatenate((a, b), axis=0)`:** The general-purpose function. It joins a sequence of arrays along an *existing* axis.
* `axis=0` joins vertically (adds more rows).
* `axis=1` joins horizontally (adds more columns).

2. **`np.vstack((a, b))`:** A convenience function for "vertical stack". It stacks arrays top-to-bottom (row-wise). It is exactly the same as `concatenate` with `axis=0`.
3. **`np.hstack((a, b))`:** A convenience function for "horizontal stack". It stacks arrays left-to-right (column-wise). It is exactly the same as `concatenate` with `axis=1`.

**The Shape Requirement (The Interview Gotcha)**  
Arrays must have the same shape, **except in the dimension corresponding to the axis you are concatenating along.**
For example, you can `vstack` (axis 0) an array of shape `(2, 5)` with an array of shape `(3, 5)` to get `(5, 5)`, but you cannot `hstack` them.

**What about `np.stack()`?**  
If an interviewer asks for the difference between `concatenate` and `stack`, remember:
* `concatenate` joins arrays along an *existing* axis (dimensions stay the same).
* `stack` joins arrays along a *new* axis (increases the dimensions, e.g., turns two 2D matrices into a single 3D tensor).

In [ ]:
import numpy as np

# Create two 2x2 matrices
arr_a = np.array([[1, 2], 
                  [3, 4]])

arr_b = np.array([[5, 6], 
                  [7, 8]])

# 1. Vertical Stacking (Adding rows)
v_concat = np.concatenate((arr_a, arr_b))
print("Vertical Concat:\n", v_concat)
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# 2. Horizontal Stacking (Adding columns)
h_concat = np.concatenate((arr_a, arr_b), axis=1)
print("\nHorizontal Concat:\n", h_concat)
# [[1 2 5 6]
#  [3 4 7 8]]

# 3. Stacking on a NEW axis 
# Turns two 2D matrices into a 3D structure (shape becomes 2, 2, 2)
new_axis_stack = np.stack((arr_a, arr_b))
print("\nNew Axis Stack:\n", new_axis_stack)
print("\nnp.stack() dimensions:", new_axis_stack.shape)

Vertical Concat:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Concat:
 [[1 2 5 6]
 [3 4 7 8]]

New Axis Stack:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

np.stack() dimensions: (2, 2, 2)


#### **18. Difference between vstack() and hstack()?**
This is a very common follow-up question. Interviewers want to verify that you have a mental model of how data is physically arranged when you combine it.

The short answer is: **`vstack()` stacks arrays vertically (top-to-bottom, adding rows), while `hstack()` stacks arrays horizontally (left-to-right, adding columns).**

**The Comparison Table**  
| Feature | `np.vstack((a, b))` (Vertical) | `np.hstack((a, b))` (Horizontal) |
| --- | --- | --- |
| **Equivalent to** | `np.concatenate((a, b), axis=0)` | `np.concatenate((a, b), axis=1)` |
| **Visual Direction** | Top-to-bottom (Row-wise) | Left-to-right (Column-wise) |
| **Shape Requirement** | Must have the exact same number of **columns**. | Must have the exact same number of **rows**. |
| **Use Case in ML** | Appending new records/samples to your dataset. | Adding new features/columns to existing data. |

**The Interview "Gotcha" (1D Arrays)**  
If you are asked what happens when you use these functions on 1D arrays (vectors), pay close attention:
* `vstack` will take two 1D arrays of shape `(N,)` and turn them into a 2D matrix of shape `(2, N)`.
* `hstack` will take two 1D arrays of shape `(N,)` and stitch them end-to-end, keeping them as a single 1D array of shape `(2N,)`.

In [ ]:
import numpy as np

# Create two 1D arrays (vectors)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 1. vstack on 1D arrays 
# Turns them into a 2D matrix (2 rows, 3 columns)
v_result = np.vstack((a, b))
print("vstack (1D inputs):\n", v_result)
print("Shape:", v_result.shape) 
# Output shape: (2, 3)


print("-" * 30)


# 2. hstack on 1D arrays 
# Stitches them end-to-end (still a 1D array)
h_result = np.hstack((a, b))
print("hstack (1D inputs):\n", h_result)
print("Shape:", h_result.shape) 
# Output shape: (6,)

vstack (1D inputs):
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
------------------------------
hstack (1D inputs):
 [1 2 3 4 5 6]
Shape: (6,)


#### **19. How to generate random numbers?**
To generate random numbers in NumPy, you use the `np.random` module. This is incredibly common in data science interviews for mocking datasets, initializing neural network weights, or splitting data.

There are three primary functions you must know, plus one critical concept for machine learning (setting the seed).

**1. The Core Random Functions**  
* **`np.random.rand(d0, d1, ...)`**: Generates random floats from a **Uniform distribution** over `[0, 1)`. All numbers have an equal chance of being picked.
* **`np.random.randn(d0, d1, ...)`**: Generates random floats from a **Standard Normal (Gaussian) distribution** (Mean = 0, Variance = 1). *Interview trick:* Remember that the 'n' in `randn` stands for "normal".
* **`np.random.randint(low, high, size)`**: Generates random **integers** from `low` (inclusive) to `high` (exclusive).

**2. The Most Important Concept: Reproducibility (`seed`)**  
If an interviewer asks, *"How do you ensure another developer gets the exact same random numbers when they run your notebook?"*, the answer is **setting the seed**.

By calling `np.random.seed(42)` before generating numbers, you lock the random number generator's state. It will produce the exact same sequence of "random" numbers every single time the script runs.

**3. Interview Bonus Points: The Modern API**  
In recent versions of NumPy, the creators recommend moving away from the global `np.random.seed()` state and instead using the new **Generator API**. Mentioning this shows you are up-to-date with best practices: `rng = np.random.default_rng(42)`.

In [ ]:
import numpy as np

# 1. The Legacy (but most common) Way 
# Lock the seed for reproducibility
np.random.seed(42)

# Uniform distribution (values between 0 and 1)
uniform_matrix = np.random.rand(2, 2)
print("Uniform (rand):\n", uniform_matrix)

# Normal distribution (centered around 0, bell curve)
normal_matrix = np.random.randn(2, 2)
print("\nNormal (randn):\n", normal_matrix)

# Random integers between 1 and 100 (exclusive of 100)
random_ints = np.random.randint(1, 100, size=(3, 3))
print("\nRandom Integers:\n", random_ints)

print("-" * 40)

# 2. The Modern Best Practice (Generator API)
# Create an isolated random number generator instance
rng = np.random.default_rng(seed=42)

# Use the modern equivalents
modern_uniform = rng.random((2, 2))       # Replaces rand()
modern_normal = rng.standard_normal((2, 2)) # Replaces randn()
modern_ints = rng.integers(1, 100, size=(3, 3)) # Replaces randint()

print("Modern Generator Integers:\n", modern_ints)

Uniform (rand):
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]]

Normal (randn):
 [[-0.23415337 -0.23413696]
 [ 1.57921282  0.76743473]]

Random Integers:
 [[22 53  2]
 [88 30 38]
 [ 2 64 60]]
----------------------------------------
Modern Generator Integers:
 [[51 13 84]
 [45 50 37]
 [19 92 78]]


#### **20. How do you copy an array? Difference between shallow and deep copy?**
In NumPy, understanding how memory is shared between variables is critical. Interviewers frequently test this to see if you can avoid bugs where modifying one array accidentally overwrites another dataset.

There are three ways to "copy" an array, each with different memory behaviors: **Assignment**, **Shallow Copy (View)**, and **Deep Copy**.

**The 3 Levels of Copying**  
| Method | Syntax | Object Identity | Underlying Data |
| --- | --- | --- | --- |
| **Assignment** | `b = a` | **Same object.** (`id(a) == id(b)`) | **Shared.** Modifying `b` changes `a`. |
| **Shallow Copy (View)** | `b = a.view()` | **New object.** | **Shared.** Modifying `b` elements still changes `a`. |
| **Deep Copy** | `b = a.copy()` | **New object.** | **Independent.** Modifying `b` does *not* change `a`. |

**The Interview "Gotcha": Slicing**  
In standard Python, slicing a list (e.g., `my_list[:]`) creates a copy. **In NumPy, slicing creates a view (shallow copy).**

If you slice a chunk out of a massive image array and alter the pixels in that chunk, the original image is altered too. If you want to safely extract and manipulate a slice without touching the original data, you *must* append `.copy()` to the slice.

In [80]:
import numpy as np

# 1. Assignment (Just a new label) 
original = np.array([1, 2, 3, 4])
assigned = original
assigned[0] = 99
print("Original after Assignment: ", original) 
# [99, 2, 3, 4] (Original is modified!)

# 2. Shallow Copy / View 
original = np.array([1, 2, 3, 4])
# Creates a new array header, but points to the same memory block
view_arr = original.view()
view_arr[0] = 99
print("Original after View:       ", original) 
# [99, 2, 3, 4] (Original is STILL modified!)

# 3. Deep Copy 
original = np.array([1, 2, 3, 4])
# Fully independent clone in memory
deep_copied = original.copy()
deep_copied[0] = 99
print("Original after Deep Copy:  ", original) 
# [1, 2, 3, 4] (Original is SAFE and unchanged)

# 4. The Slicing Gotcha
original = np.array([1, 2, 3, 4])
my_slice = original[1:3]  # This is a VIEW!
my_slice[0] = 999
print("Original after modifying slice:", original)
# [1, 999, 3, 4] (Original is modified!)

Original after Assignment:  [99  2  3  4]
Original after View:        [99  2  3  4]
Original after Deep Copy:   [1 2 3 4]
Original after modifying slice: [  1 999   3   4]


## Intermediate Level (21–50)

#### **21. What is array indexing?**
**Array Indexing** is the method used to access or modify individual elements (or groups of elements) stored within a NumPy array.

Just like standard Python lists, NumPy arrays use **zero-based indexing**, meaning the first element is at position `0`, the second is at `1`, and so on.

**The NumPy Difference: Multi-Dimensional Indexing**  
While a standard Python nested list requires you to chain brackets together (e.g., `my_list[0][1]`), NumPy allows you to use a single set of brackets with comma-separated indices (e.g., `my_array[0, 1]`). This is much faster and cleaner.

What interviewers look for when testing your indexing knowledge:
1. **1D Indexing:** Standard `arr[i]` syntax.
2. **2D Indexing (Matrices):** `arr[row, column]` syntax.
3. **Negative Indexing:** Using negative numbers to count from the end of the array backwards (e.g., `-1` is the last element, `-2` is the second-to-last).

In [ ]:
import numpy as np

# 1. 1D Array Indexing 
arr_1d = np.array([10, 20, 30, 40, 50])

print("First element: ", arr_1d[0])   # Output: 10
print("Last element:  ", arr_1d[-1])  # Output: 50 (Negative indexing)

# 2. 2D Array Indexing (Matrix) 
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Standard Python way (works, but is slow and not recommended for NumPy)
print("\nStandard Python access:", arr_2d[1][2]) # Row 1, Col 2 -> Output: 6
print("Standard Python access:", arr_2d[:][2]) # Row 2 -> Output: [7 8 9]
print("Standard Python access:", arr_2d[1][:]) # Row 1 -> Output: [4 5 6]

# The NumPy way (Comma-separated)
print("\nNumPy access:          ", arr_2d[1, 2]) # Row 1, Col 2 -> Output: 6
print("NumPy access:          ", arr_2d[2]) # Row 2 -> Output: [7 8 9]
print("NumPy access:          ", arr_2d[:, 2]) # Row 2 -> Output: [3 6 9]

# Mixing positive and negative indices
# Last row, second column
print("\nMixed indexing:        ", arr_2d[-1, 1]) # Output: 8

First element:  10
Last element:   50

Standard Python access: 6
Standard Python access: [7 8 9]
Standard Python access: [4 5 6]

NumPy access:           6
NumPy access:           [7 8 9]
NumPy access:           [3 6 9]

Mixed indexing:         8


#### **22. What is slicing?**
**Slicing** is the method of extracting a specific subset of elements from an array. It allows you to grab sections, rows, columns, or skip over elements without creating entirely new datasets from scratch.

**The Slicing Syntax**  
The core syntax for a single dimension is `[start:stop:step]`.
* **`start` (Inclusive):** The index where the slice begins (defaults to `0`).
* **`stop` (Exclusive):** The index where the slice ends (defaults to the end of the array).
* **`step`:** The jump size between elements (defaults to `1`).

For a 2D array, you simply separate the dimensions with a comma: `[row_start:row_stop, col_start:col_stop]`.

**The Interview "Gotcha": Slicing Returns a View!**  
This is arguably the most common bug in NumPy code, and interviewers *will* ask about it.

When you slice a standard Python list, Python creates a brand new copy of that data. **When you slice a NumPy array, it returns a *view* of the original memory block.** This makes NumPy incredibly fast and memory-efficient. However, if you modify the slice, **you modify the original array.**

If you need an independent slice that won't corrupt your original dataset, you must explicitly use `.copy()` (e.g., `my_slice = arr[0:2].copy()`).

> **Key insight:** You can completely drop the `start` or `stop` values if you want to go all the way to the edge. For example, `[:3]` means "from the start up to index 3," and `[2:]` means "from index 2 to the end."

In [93]:
import numpy as np

# 1. 1D Slicing
arr_1d = np.array([10, 20, 30, 40, 50, 60])

print("Slice [1:4]:   ", arr_1d[1:4])   # Output: [20 30 40]
print("Slice [:3]:    ", arr_1d[:3])    # Output: [10 20 30] (Start to 3)
print("Slice [::2]:   ", arr_1d[::2])   # Output: [10 30 50] (Step by 2)
print("Reverse [::-1]:", arr_1d[::-1])  # Output: [60 50 40 30 20 10]

print("-" * 30)

# 2. 2D Slicing (Matrices)
arr_2d = np.array([[ 1,  2,  3,  4],
                   [ 5,  6,  7,  8],
                   [ 9, 10, 11, 12]])

# Get the first two rows, and columns from index 1 to 3
print("Sub-matrix:\n", arr_2d[0:2, 1:3])
# [[2 3]
#  [6 7]]

# Get ALL rows (using :), but only the last column
print("\nLast Column:\n", arr_2d[:, -1])
# [ 4  8 12]

print("-" * 30)

# 3. The 'View' Proof 
original = np.array([1, 2, 3, 4, 5])
my_slice = original[1:4]

# Modify the slice
my_slice[0] = 999 

print("Modified Slice:  ", my_slice)    # [999, 3, 4]
print("Corrupted Original:", original)  # [1, 999, 3, 4, 5] (Original changed!)

Slice [1:4]:    [20 30 40]
Slice [:3]:     [10 20 30]
Slice [::2]:    [10 30 50]
Reverse [::-1]: [60 50 40 30 20 10]
------------------------------
Sub-matrix:
 [[2 3]
 [6 7]]

Last Column:
 [ 4  8 12]
------------------------------
Modified Slice:   [999   3   4]
Corrupted Original: [  1 999   3   4   5]


#### **23. What is boolean indexing?**
**Boolean Indexing** (also known as Boolean Masking) is an incredibly powerful feature in NumPy that allows you to filter an array based on logical conditions without writing any loops.

Instead of selecting elements by their index number (like `arr[0]`), you select them by passing a "mask" of `True` and `False` values. NumPy will extract and return only the elements where the mask is `True`.

**How It Works (The 2-Step Process)**  
1. **Create the Condition:** Use standard comparison operators (`>`, `<`, `==`, `!=`) on the array. Because NumPy is vectorized, this instantly returns a new array of the same shape filled with `True` or `False`.
2. **Apply the Mask:** Place that boolean array inside the indexing brackets `[]`.

**Combining Conditions**  
You can combine multiple conditions using bitwise operators.
* **Interview Gotcha:** You *must* use bitwise `&` (and) or `|` (or). Using Python's standard `and` / `or` keywords will result in a `ValueError`.
* You must also wrap each condition in parentheses `()`.

In [94]:
import numpy as np

# Sample dataset (e.g., ages of people)
ages = np.array([18, 25, 14, 45, 12, 60, 32])

# 1. The Step-by-Step Way
# Create the boolean mask (True if age >= 18)
is_adult = ages >= 18 
print("The Boolean Mask: ", is_adult)
# [ True  True False  True False  True  True]

# Apply the mask
adults = ages[is_adult]
print("Filtered (Adults):", adults)
# [18 25 45 60 32]

print("-" * 30)

# 2. The Idiomatic (One-Liner) Way
# This is how you will actually write it in production/interviews
seniors = ages[ages >= 60]
print("Filtered (Seniors):", seniors)
# [60]

print("-" * 30)

# 3. Multiple Conditions (& and |)
# Find people who are in their 20s OR early 30s
# Note the parentheses and the bitwise operators!
target_demo = ages[(ages >= 20) & (ages <= 35)]
print("Target Demo (20-35):", target_demo)
# [25 32]

print("-" * 30)

# 4. Modifying Data using Boolean Indexing
# Replace all minors with 0
ages[ages < 18] = 0
print("Data after replacement:", ages)
# [18 25  0 45  0 60 32]

The Boolean Mask:  [ True  True False  True False  True  True]
Filtered (Adults): [18 25 45 60 32]
------------------------------
Filtered (Seniors): [60]
------------------------------
Target Demo (20-35): [25 32]
------------------------------
Data after replacement: [18 25  0 45  0 60 32]


#### **24. What is fancy indexing?**
**Fancy Indexing** is a NumPy term for passing an *array* of indices to access multiple specific elements at once.

While standard slicing requires you to select elements in a predictable pattern (e.g., "start here, stop here, step by 2"), fancy indexing allows you to pluck elements completely out of order, skip around, or even select the same element multiple times.

**Slicing vs. Fancy Indexing (Interview Focus)**  
| Feature | Basic Slicing (`arr[1:4]`) | Fancy Indexing (`arr[[1, 3, 2]]`) |
| --- | --- | --- |
| **Selection Type** | Must be continuous or evenly spaced. | Arbitrary, out-of-order, or repeated. |
| **Input Format** | `start:stop:step` | A Python list or NumPy array of integers. |
| **Memory Behavior** | Returns a **View** (modifying changes original). | Returns a **Copy** (modifying is safe). |


**The 2D Coordinate Gotcha**  
When applying fancy indexing to a 2D matrix, passing two arrays of indices pairs them up like `(x, y)` coordinates.
For example, `arr[[0, 2], [1, 3]]` does *not* grab a square of elements. It grabs exactly two elements: the one at row 0, col 1, and the one at row 2, col 3.


In [95]:
import numpy as np

# --- 1. 1D Fancy Indexing ---
arr_1d = np.array([10, 20, 30, 40, 50])

# Grab the 4th, 1st, and 4th elements (Notice the double brackets!)
# Outer brackets are for indexing, inner brackets are the list of indices
fancy_selection = arr_1d[[3, 0, 3]]
print("1D Fancy Result:", fancy_selection) 
# Output: [40 10 40]

print("-" * 30)

# --- 2. Selecting Specific Rows in 2D ---
matrix = np.array([[ 1,  2,  3],
                   [ 4,  5,  6],
                   [ 7,  8,  9],
                   [10, 11, 12]])

# Select Row 3, then Row 0, then Row 3 again
row_selection = matrix[[3, 0, 3]]
print("Selected Rows:\n", row_selection)
# [[10 11 12]
#  [ 1  2  3]
#  [10 11 12]]

print("-" * 30)

# --- 3. The Coordinate Selection (Gotcha) ---
# Select element at (row 0, col 0) AND element at (row 2, col 2)
coordinate_selection = matrix[[0, 2], [0, 2]]
print("Coordinate Elements:", coordinate_selection)
# Output: [1 9]

1D Fancy Result: [40 10 40]
------------------------------
Selected Rows:
 [[10 11 12]
 [ 1  2  3]
 [10 11 12]]
------------------------------
Coordinate Elements: [1 9]


#### **25. How to filter values greater than X?**
To filter values greater than a specific threshold `X`, you use **Boolean Indexing** (also called Boolean Masking). This is the standard, vectorized way to filter data in NumPy without writing slow Python `for` loops.

**The Idiomatic Approach**  
The most common and expected answer in an interview is the one-liner: **`filtered_array = arr[arr > X]`**.

How it works under the hood:
1. **`arr > X`**: NumPy vectorizes the comparison, checking every single element against `X`. It instantly returns a new array of the same shape, filled with `True` (if the condition is met) or `False` (if it isn't).
2. **`arr[...]`**: When you pass that `True`/`False` array back into the original array's brackets, NumPy filters out all the `False` valuesAssuming you are working with data, the exact method depends on the programming language or tool you are using. 

In [99]:
# 1. 1D Array 
arr_1d = np.array([10, 20, 30, 40, 50])
print("Actual Array:   ", arr_1d)

# 2. Filtered Values 
print("Filtered Values:", arr_1d>20)

# 3. Filtered Array 
print("Filtered Array: ", arr_1d[arr_1d>20])

Actual Array:    [10 20 30 40 50]
Filtered Values: [False False  True  True  True]
Filtered Array:  [30 40 50]


#### **26. How to replace values conditionally?**
Replacing values conditionally in NumPy is a staple of data cleaning tasks, such as replacing negative numbers with zeros or capping extreme outliers.

There are two primary ways to do this, and the interviewer expects you to know the difference in their memory behaviors.

**1. In-Place Replacement (Boolean Masking)**  
If you want to modify the *existing* array directly, you use standard Boolean Indexing combined with assignment (`=`).
* **Syntax:** `arr[condition] = new_value`
* **Pros:** Fast and memory efficient because it modifies the data in-place without creating a copy.
* **Cons:** You lose the original data.

**2. Returning a New Array (`np.where`)**  
If you want to keep the original array intact and return a *new* array based on an if-else condition, you use **`np.where()`**. This function is the vectorized equivalent of a Python ternary operator (`x if condition else y`).
* **Syntax:** `np.where(condition, value_if_true, value_if_false)`
* **Pros:** Leaves the original array untouched. Extremely flexible (you can pull values from other arrays for the true/false arguments).

**3. Interview Bonus: np.clip()**  
Interviewers love when you know this shortcut for capping outliers!
"Keep all numbers between 0 and 10. Anything lower becomes 0, anything higher becomes 10."
data_3 = np.array([-50, 5, 8, 100])In NumPy, there are two primary ways to replace values based on a condition. The method you choose depends on whether you want to modify the array **in-place** or create a **new array**.

**1. `np.where()` (Creates a New Array)**  
`np.where` is the vectorized equivalent of an `if-else` statement. It evaluates a condition and selects elements from a "true" value or a "false" value.  
**Syntax:** `np.where(condition, true_value, false_value)`

*Note: You can also use arrays for the `true_value` and `false_value` arguments to pull elements from different arrays conditionally.*

**2. Boolean Masking (In-Place Modification)**  
If you want to modify the existing array without allocating new memory, use boolean indexing. You pass the condition inside the brackets and assign the new value.

In [ ]:
import numpy as np

# 1. Boolean Masking (In-Place)
data_1 = np.array([-10, 15, -5, 20])
# Replace all negative numbers with 0
data_1[data_1 < 0] = 0
print("In-Place Replacement: ", data_1)
# Output: [ 0 15  0 20] (Original array is permanently changed)

print("-" * 30)

# 2. np.where (Returns a Copy)
data_2 = np.array([-10, 15, -5, 20])
# "If value is < 0, replace with 0. Else, keep the original value."
cleaned_data = np.where(data_2 < 0, 0, data_2)
print("Original data intact: ", data_2) 
# Output: [-10  15  -5  20]
print("New cleaned array:    ", cleaned_data)
# Output: [ 0 15  0 20]

In-Place Replacement:  [ 0 15  0 20]
------------------------------
Original data intact:  [-10  15  -5  20]
New cleaned array:     [ 0 15  0 20]


In [ ]:
import numpy as np

arr = np.array([1, -5, 3, -2, 8])
# Replace negative numbers with 0, keep positive numbers as they are
new_arr = np.where(arr < 0, 0, arr)
print(new_arr)
# Output: [1 0 3 0 8]

arr = np.array([1, -5, 3, -2, 8])
# Replace all values greater than 2 with 99
arr[arr > 2] = 99
print(arr)
# Output: [ 1 -5 99 -2 99]

[1 0 3 0 8]
[ 1 -5 99 -2 99]


#### **27. What is the difference between ravel() and flatten()?**

#### **28. What is axis in NumPy?**

#### **29. Explain axis=0 vs axis=1.**

#### **30. How do you compute mean, median, std?**

#### **31. How to find unique elements?**

#### **32. How to count occurrences?**

#### **33. How to sort an array?**

#### **34. Difference between sort() and argsort()?**

#### **35. How to find index of max/min?**

#### **36. What is where() used for?**

#### **37. What is np.clip()?**

#### **38. What is np.cumsum() and np.cumprod()?**

#### **39. How do you reverse an array?**

#### **40. What is broadcasting rule?**

#### **41. When does broadcasting fail?**

#### **42. How do you transpose a matrix?**

#### **43. What is np.newaxis?**

#### **44. How to expand dimensions?**

#### **45. How to squeeze dimensions?**

#### **46. What is np.meshgrid()?**

#### **47. How to handle NaN values?**

#### **48. Difference between isnan() and isfinite()?**

#### **49. What are universal functions (ufuncs)?**

#### **50. How do ufuncs improve performance?**

## Linear Algebra Level (51–65)

#### **51. What module is used for linear algebra?**

#### **52. How to compute dot product?**

#### **53. Difference between dot and matmul?**

#### **54. How to compute matrix inverse?**

#### **55. When does inverse not exist?**

#### **56. What is determinant?**

#### **57. How to compute determinant?**

#### **58. What are eigenvalues and eigenvectors?**

#### **59. How to compute eigenvalues?**

#### **60. What is SVD?**

#### **61. How to solve linear equations?**

#### **62. What is pseudo-inverse?**

#### **63. What is condition number?**

#### **64. What is Frobenius norm?**

#### **65. How to compute matrix rank?**

## Performance & Memory (66–80)

#### **66. Why is NumPy faster than Python lists?**


#### **67. What is contiguous memory?**


#### **68. What are strides?**


#### **69. How to check memory usage of an array?**


#### **70. What is memory layout (C vs F order)?**


#### **71. What is broadcasting efficiency?**


#### **72. What are views?**


#### **73. What operations return views vs copies?**


#### **74. How to avoid unnecessary copies?**


#### **75. What is vectorization vs loop?**


#### **76. What is np.frombuffer()?**


#### **77. What is np.memmap()?**


#### **78. How to optimize large array computations?**


#### **79. When to use NumPy vs Pandas?**


#### **80. How NumPy interacts with C internally?**


## Advanced Level (81–95)

#### **81. What are structured arrays?**


#### **82. What is masked array?**


#### **83. What is einsum()?**


#### **84. How does einsum() optimize computation?**


#### **85. What is broadcasting with higher dimensions?**


#### **86. What is advanced indexing performance impact?**


#### **87. What is np.lib.stride_tricks?**


#### **88. How does NumPy handle type promotion?**


#### **89. What is object dtype?**


#### **90. What are memory views?**


#### **91. What is np.vectorize() and is it truly vectorized?**


#### **92. What is np.apply_along_axis()?**


#### **93. How to implement custom ufunc?**


#### **94. What is BLAS/LAPACK usage in NumPy?**


#### **95. What are numerical stability issues in NumPy?**


## Expert / Interview Case-Based (96–100)

#### **96. Implement softmax using NumPy (numerically stable).**


#### **97. Implement gradient descent using NumPy.**


#### **98. Normalize dataset column-wise without loops.**
 

#### **99. Find pairwise Euclidean distance matrix efficiently.**


#### **100. Implement PCA using only NumPy.**


## Conceptual Deep Interview Questions

#### **101. Why is NumPy core to libraries like pandas?**


#### **102. How does NumPy support frameworks like TensorFlow and PyTorch?**


#### **103. Why is vectorization critical in ML pipelines?**
