## Basic Level (1-20)

#### 1. What is NumPy and why is it used?
- NumPy or "Numerical Python" is a python library used for numerical calculations in python. And NumPy is very fast in terms of numerical calculations. We can use NumPy in python as mentioned below.

In [1]:
import numpy as np

#### 2. What is an ndarray?
- Array in NumPy is an one dimensional array. ndarray is n dimentional array in NumPy.

In [26]:
a = np.ndarray(shape=(3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 3. Difference between Python list and NumPy array?
- The main difference between Python list and NumPy array is mentioned below in terms of speed(NumPy Array is Faster) and element datatypes(NumPy array can only take numbers)

In [12]:
%time np.array([1, 2, 3, 4])
%time list([1, 2, 3, 4])

%time np.array([1.0, 2.0, 3.0, 4.0])
%time list([1.0, 2.0, 3.0, 4.0])

%time np.array([1.0/2, 2.0/2, 3.0/2, 4.0/2])
%time list([1.0/2, 2.0/2, 3.0/2, 4.0/2])

CPU times: user 21 μs, sys: 0 ns, total: 21 μs
Wall time: 21.9 μs
CPU times: user 2 μs, sys: 1e+03 ns, total: 3 μs
Wall time: 4.05 μs
CPU times: user 7 μs, sys: 0 ns, total: 7 μs
Wall time: 8.11 μs
CPU times: user 1 μs, sys: 0 ns, total: 1 μs
Wall time: 1.67 μs
CPU times: user 3 μs, sys: 1 μs, total: 4 μs
Wall time: 3.81 μs
CPU times: user 1 μs, sys: 0 ns, total: 1 μs
Wall time: 3.1 μs


[0.5, 1.0, 1.5, 2.0]

In [21]:
%time print(np.array([1, 2.5, "Data Science", {1: "toy", 2: "ball"}]))
%time print(list([1, 2.5, "Data Science", {1: "toy", 2: "ball"}]))

[1 2.5 'Data Science' {1: 'toy', 2: 'ball'}]
CPU times: user 139 μs, sys: 6 μs, total: 145 μs
Wall time: 142 μs
[1, 2.5, 'Data Science', {1: 'toy', 2: 'ball'}]
CPU times: user 18 μs, sys: 1 μs, total: 19 μs
Wall time: 20.3 μs


#### 4. How do you create a NumPy array?

In [22]:
import numpy as np
a = np.array([1, 2, 5, 4.3, 33.0])
print(a, type(a))

[ 1.   2.   5.   4.3 33. ] <class 'numpy.ndarray'>


#### 5. What is the difference between np.array() and np.asarray()?

In [ ]:
import numpy as np

original_array = np.array([1, 3, 5, 7])
new_array = np.array(original_array) # Always makes a copy in the memory
print(original_array)
print(new_array)

original_array[0] = 99
print(original_array)
print(new_array)

[1 3 5 7]
[1 3 5 7]
[99  3  5  7]
[1 3 5 7]


In [ ]:
import numpy as np

original_array = np.array([1, 3, 5, 7])
new_array = np.asarray(original_array) # Uses the same memory location as the original_array(the datatype should be same)
print(original_array)
print(new_array)

original_array[0] = 99
print(original_array)
print(new_array)

[1 3 5 7]
[1 3 5 7]
[99  3  5  7]
[99  3  5  7]


#### 6. How do you check the shape of an array?

In [24]:
a = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
print(a)
print(a.shape)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
(3, 3)


#### 7. How do you check the datatype of elements?

In [32]:
a = np.ndarray((2,3))
print(a)
print(type(a))

b = {"a": 100, "b": 200}
print(b)
print(type(b))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
{'a': 100, 'b': 200}
<class 'dict'>


#### 8. What is dtype in NumPy?

In [41]:
a = np.array([1, 2, 4, 110], dtype=float)
b = np.array([1, 2, 4, 110], dtype=int)
c = np.array([1, 2.5, 33.33, 4.9],dtype=int)
print(a)
print(b)
print(c)

[  1.   2.   4. 110.]
[  1   2   4 110]
[ 1  2 33  4]


#### 9. How to create:
- Zeros array?
- Ones array?
- Identity matrix?

In [43]:
a = np.zeros(5)
print(a)

b = np.ones(4)
print(b)

c = np.identity(3)
print(c)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 10. What is the difference between np.arange() and np.linspace()?

In [51]:
a = np.arange(3, 12, 3)
print(a)

b = np.linspace(3, 12, 3)
print(b)

[3 6 9]
[ 3.   7.5 12. ]


#### 11. How do you reshape an array?

In [58]:
a = np.ones(12)
print(a, a.shape)

b = a.reshape((4, 3))
print(b, b.shape)

c = a.reshape((3, -1))
print(c, c.shape)

# d = a.reshape((5, -1))    # Cannot be reshaped because 5 is not a divisor of 12

e = np.array([[1, 2], [3, 4], [5, 6]])
print(e, e.shape)
print(e.reshape(2, 3))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] (12,)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (4, 3)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 2 3]
 [4 5 6]]


#### 12. What is the difference between reshape() and resize()?

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a, a.shape)
print(a.reshape(4, 3))

print(np.resize(a, (11, 2)))    # growing or shrinking the array

a.resize((4, 6))
print(a)    # it alters the original array directly

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


#### 13. What is broadcasting?
- Broadcasting is NumPy's mechanism for performing element-wise operations on arrays of different shapes by virtually "stretching" the smaller array to match the dimensions of the larger one without actually copying memory.

In [71]:
# The scalar 10 is broadcast (stretched) into [10, 10, 10] to match the array's shape
a = np.array([1, 2, 3]) + 10 
print(a) 

[11 12 13]


#### 14. What is vectorization?
- Vectorization is the practice of replacing explicit Python for loops with NumPy array operations, shifting the mathematical computations to highly optimized, pre-compiled C code for drastically faster performance.

In [73]:
a = np.array([1, 2, 3, 4])
b = 6
# The vectorized approach multiplies the entire array at once, entirely avoiding a slow Python 'for' loop.
print(a*2)
print(a*b)

[2 4 6 8]
[ 6 12 18 24]


#### 15. How to perform element-wise operations?

In [74]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+b)  
print(a*b)  
print(a-5)
print(a**b)
print(np.sqrt(a))
print(np.square(b))
print(np.sin(a))

[5 7 9]
[ 4 10 18]
[-4 -3 -2]
[  1  32 729]
[1.         1.41421356 1.73205081]
[16 25 36]
[0.84147098 0.90929743 0.14112001]


## Intermediate Level (21–50)

## Linear Algebra Level (51–65)

## Performance & Memory (66–80)

## Advanced Level (81–95)

## Expert / Interview Case-Based (96–100)