## Basic Level (1-20)

#### **1. What is NumPy and why is it used?**
**NumPy (Numerical Python)** is the foundational library for scientific and numerical computing in Python. It introduces a highly efficient, multi-dimensional array object called `ndarray` and provides a vast collection of mathematical functions to operate on these arrays.

* **Blazing Fast Performance (Vectorization):** Under the hood, NumPy is written in C. It uses **vectorization** to apply operations to entire arrays at once, entirely bypassing Python's slow `for` loops and interpreter overhead.

* **Contiguous Memory Allocation:** Unlike standard Python lists, which are basically arrays of memory pointers pointing to scattered objects, NumPy arrays store elements of the same data type (`dtype`) in single, continuous blocks of memory. This makes fetching and processing data exponentially faster.

* **Broadcasting:** NumPy features a powerful mathematical engine that automatically handles operations between arrays of different shapes and sizes without needing to replicate data in memory.

* **The Ecosystem Foundation:** Almost every major data science and machine learning library in Python (Pandas, SciPy, Scikit-learn, TensorFlow) relies on NumPy arrays as their underlying data structure.

In [1]:
# Importing NumPy Library in Python
import numpy as np

#### **2. What is an ndarray?**
An **`ndarray` (N-dimensional array)** is the central data structure of the NumPy library. It is a fast, flexible container designed to hold large datasets and perform mathematical operations on them efficiently.

**Key Characteristics of an ndarray:**
* **Homogeneous Data:** Every element inside an `ndarray` must be of the exact same data type (e.g., all 32-bit integers, or all 64-bit floats). Because the data type is uniform, NumPy doesn't have to waste time checking the type of every single element before operating on it.

* **Fixed Size:** Unlike standard Python lists which can grow or shrink dynamically, an `ndarray` has a fixed size created at initialization. If you need to change its size (like appending elements), NumPy typically creates a brand new array under the hood.

* **Strided Memory:** Data is stored in a continuous block of memory. The `ndarray` object acts as a "view" that tells Python exactly how to interpret that raw memory (using "strides") to read it as a 1D vector, 2D matrix, or multi-dimensional tensor.

**Must-Know Attributes for Interviews:**
If an interviewer asks how you would inspect a mysterious dataset loaded into a NumPy array, you should immediately mention checking these attributes:

* **`.ndim`**: Returns the number of dimensions (axes).
* **`.shape`**: Returns a tuple showing the size of the array across each dimension (e.g., `(100, 5)` for 100 rows and 5 columns).
* **`.size`**: Returns the total number of elements in the entire array.
* **`.dtype`**: Returns the specific data type of the array's elements (e.g., `float64`, `int32`).

In [ ]:
import numpy as np

# Creating an ndarray from a nested Python list (2D Matrix)
data = [[1, 2, 3], 
        [4, 5, 6]]
arr_2d = np.array(data)

print("Target Array:\n", arr_2d)
print("-" * 30)

# Inspecting the crucial attributes (The "Diagnostic Check")
print("Object Type:  ", type(arr_2d))       # <class 'numpy.ndarray'>
print("Dimensions:   ", arr_2d.ndim)        # 2 (since it's a matrix)
print("Shape:        ", arr_2d.shape)       # (2, 3) -> 2 rows, 3 columns
print("Total Size:   ", arr_2d.size)        # 6 elements total
print("Data Type:    ", arr_2d.dtype)       # int32 or int64
print("-" * 30)

# Allocate uninitialized memory
a = np.ndarray(shape=(3, 4)) 
# Overwrite everything using slice assignment [:]
a[:] = [
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]]

print("Using ndarray:\n", a)

Target Array:
 [[1 2 3]
 [4 5 6]]
------------------------------
Object Type:   <class 'numpy.ndarray'>
Dimensions:    2
Shape:         (2, 3)
Total Size:    6
Data Type:     int64
------------------------------
Using ndarray:
 [[ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [ 90. 100. 110. 120.]]


#### **3. Difference between Python list and NumPy array?**
- The main difference between Python list and NumPy array is mentioned below in terms of speed(NumPy Array is Faster) and element datatypes(NumPy array can only take numbers)

In [3]:
%time np.array([1, 2, 3, 4])
%time list([1, 2, 3, 4])

%time np.array([1.0, 2.0, 3.0, 4.0])
%time list([1.0, 2.0, 3.0, 4.0])

%time np.array([1.0/2, 2.0/2, 3.0/2, 4.0/2])
%time list([1.0/2, 2.0/2, 3.0/2, 4.0/2])

CPU times: user 19 μs, sys: 111 μs, total: 130 μs
Wall time: 21 μs
CPU times: user 3 μs, sys: 19 μs, total: 22 μs
Wall time: 2.86 μs
CPU times: user 9 μs, sys: 55 μs, total: 64 μs
Wall time: 10.7 μs
CPU times: user 2 μs, sys: 14 μs, total: 16 μs
Wall time: 6.91 μs
CPU times: user 4 μs, sys: 26 μs, total: 30 μs
Wall time: 4.77 μs
CPU times: user 2 μs, sys: 13 μs, total: 15 μs
Wall time: 3.1 μs


[0.5, 1.0, 1.5, 2.0]

In [4]:
%time print(np.array([1, 2.5, "Data Science", {1: "toy", 2: "ball"}]))
%time print(list([1, 2.5, "Data Science", {1: "toy", 2: "ball"}]))

[1 2.5 'Data Science' {1: 'toy', 2: 'ball'}]
CPU times: user 190 μs, sys: 802 μs, total: 992 μs
Wall time: 130 μs
[1, 2.5, 'Data Science', {1: 'toy', 2: 'ball'}]
CPU times: user 28 μs, sys: 135 μs, total: 163 μs
Wall time: 18.8 μs


#### **4. How do you create a NumPy array?**

In [5]:
import numpy as np
a = np.array([1, 2, 5, 4.3, 33.0])
print(a, type(a))

[ 1.   2.   5.   4.3 33. ] <class 'numpy.ndarray'>


#### **5. What is the difference between np.array() and np.asarray()?**

In [6]:
import numpy as np

original_array = np.array([1, 3, 5, 7])
new_array = np.array(original_array) # Always makes a copy in the memory
print(original_array)
print(new_array)

original_array[0] = 99
print(original_array)
print(new_array)

[1 3 5 7]
[1 3 5 7]
[99  3  5  7]
[1 3 5 7]


In [7]:
import numpy as np

original_array = np.array([1, 3, 5, 7])
new_array = np.asarray(original_array) # Uses the same memory location as the original_array(the datatype should be same)
print(original_array)
print(new_array)

original_array[0] = 99
print(original_array)
print(new_array)

[1 3 5 7]
[1 3 5 7]
[99  3  5  7]
[99  3  5  7]


#### **6. How do you check the shape of an array?**

In [8]:
a = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
print(a)
print(a.shape)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
(3, 3)


#### **7. How do you check the datatype of elements?**

In [9]:
a = np.ndarray((2,3))
print(a)
print(type(a))

b = {"a": 100, "b": 200}
print(b)
print(type(b))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
{'a': 100, 'b': 200}
<class 'dict'>


#### **8. What is dtype in NumPy?**

In [10]:
a = np.array([1, 2, 4, 110], dtype=float)
b = np.array([1, 2, 4, 110], dtype=int)
c = np.array([1, 2.5, 33.33, 4.9],dtype=int)
print(a)
print(b)
print(c)

[  1.   2.   4. 110.]
[  1   2   4 110]
[ 1  2 33  4]


#### **9. How to create:**
- Zeros array?
- Ones array?
- Identity matrix?

In [11]:
a = np.zeros(5)
print(a)

b = np.ones(4)
print(b)

c = np.identity(3)
print(c)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### **10. What is the difference between np.arange() and np.linspace()?**

In [12]:
a = np.arange(3, 12, 3)
print(a)

b = np.linspace(3, 12, 3)
print(b)

[3 6 9]
[ 3.   7.5 12. ]


#### **11. How do you reshape an array?**

In [13]:
a = np.ones(12)
print(a, a.shape)

b = a.reshape((4, 3))
print(b, b.shape)

c = a.reshape((3, -1))
print(c, c.shape)

# d = a.reshape((5, -1))    # Cannot be reshaped because 5 is not a divisor of 12

e = np.array([[1, 2], [3, 4], [5, 6]])
print(e, e.shape)
print(e.reshape(2, 3))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] (12,)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (4, 3)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 2 3]
 [4 5 6]]


#### **12. What is the difference between reshape() and resize()?**

In [14]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a, a.shape)
print(a.reshape(4, 3))

print(np.resize(a, (11, 2)))    # growing or shrinking the array

a.resize((4, 6))
print(a)    # it alters the original array directly

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


#### **13. What is broadcasting?**
- Broadcasting is NumPy's mechanism for performing element-wise operations on arrays of different shapes by virtually "stretching" the smaller array to match the dimensions of the larger one without actually copying memory.

In [15]:
# The scalar 10 is broadcast (stretched) into [10, 10, 10] to match the array's shape
a = np.array([1, 2, 3]) + 10 
print(a) 

[11 12 13]


#### **14. What is vectorization?**
- Vectorization is the practice of replacing explicit Python for loops with NumPy array operations, shifting the mathematical computations to highly optimized, pre-compiled C code for drastically faster performance.

In [16]:
a = np.array([1, 2, 3, 4])
b = 6
# The vectorized approach multiplies the entire array at once, entirely avoiding a slow Python 'for' loop.
print(a*2)
print(a*b)

[2 4 6 8]
[ 6 12 18 24]


#### **15. How to perform element-wise operations?**

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+b)  
print(a*b)  
print(a-5)
print(a**b)
print(np.sqrt(a))
print(np.square(b))
print(np.sin(a))

[5 7 9]
[ 4 10 18]
[-4 -3 -2]
[  1  32 729]
[1.         1.41421356 1.73205081]
[16 25 36]
[0.84147098 0.90929743 0.14112001]


#### **16. What is the difference between * and dot()?**

In [18]:
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])

print(a*b)
print(a.dot(b))

[ 2 12 30]
44


#### **17. How do you concatenate arrays?**

In [19]:
a = np.array([1, 2, 3, 4]).reshape((2, 2))
print(a)
print(np.concatenate([a, a, a], axis=0))
print(np.concatenate([a, a, a], axis=1))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]


#### **18. Difference between vstack() and hstack()?**

In [20]:
a = np.array([1, 2, 3, 4])
print(np.vstack([a, a, a]))
print(np.hstack([a, a, a]))

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[1 2 3 4 1 2 3 4 1 2 3 4]


#### **19. How to generate random numbers?**

In [21]:
a = np.random.randint(1, 10, (2, 3))
print(a)

[[3 4 1]
 [9 1 2]]


#### **20. How do you copy an array? Difference between shallow and deep copy?**

In [22]:
a = np.array([1, 2, 3, 4])
b = a.copy()    # Deep Copy
c = a.view()    # Shallow Copy / c = a
print(a)
print(b)
print(c)

b[0] = 9    # Independently created the array in new memory location
print(a)
print(b)
print(c)

c[0] = 9    # Sharing the same memory location
print(a)
print(b)
print(c)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[9 2 3 4]
[1 2 3 4]
[9 2 3 4]
[9 2 3 4]
[9 2 3 4]


## Intermediate Level (21–50)

#### **21. What is array indexing?**

In [23]:
import numpy as np

a = np.random.randint(0, 9, 3)
b = np.random.randint(0, 9, (3, 3))
c = np.random.randint(0, 9, (2, 3, 3))
print(a)
print(b)
print(c)

print(a[1])
print(b[1], b[[1, 1]])
print(c[1], c[[1, 1]], c[[1, 1, 1]])

[8 1 3]
[[1 7 1]
 [5 3 3]
 [5 5 4]]
[[[6 4 1]
  [7 3 3]
  [5 2 3]]

 [[1 5 8]
  [2 3 7]
  [0 4 1]]]
1
[5 3 3] [[5 3 3]
 [5 3 3]]
[[1 5 8]
 [2 3 7]
 [0 4 1]] [[[1 5 8]
  [2 3 7]
  [0 4 1]]

 [[1 5 8]
  [2 3 7]
  [0 4 1]]] [[[1 5 8]
  [2 3 7]
  [0 4 1]]

 [[1 5 8]
  [2 3 7]
  [0 4 1]]

 [[1 5 8]
  [2 3 7]
  [0 4 1]]]


#### **22. What is slicing?**

In [24]:
import numpy as np

a = np.random.randint(0, 9, 4)
b = np.random.randint(0, 9, (3, 4))
c = np.random.randint(0, 9, (2, 3, 4))
print(a)
print(b)
print(c)

print(a[1:2])
print(b[1:2], )
print(c[:][0:1][1:2])

[5 5 5 3]
[[7 4 6 8]
 [2 4 6 8]
 [7 3 3 6]]
[[[5 4 8 2]
  [0 7 3 4]
  [1 5 8 6]]

 [[6 5 5 6]
  [1 6 0 2]
  [3 7 1 5]]]
[5]
[[2 4 6 8]]
[]


#### **23. What is boolean indexing?**

#### **24. What is fancy indexing?**

#### **25. How to filter values greater than X?**

#### **26. How to replace values conditionally?**

#### **27. What is the difference between ravel() and flatten()?**

#### **28. What is axis in NumPy?**

#### **29. Explain axis=0 vs axis=1.**

#### **30. How do you compute mean, median, std?**

#### **31. How to find unique elements?**

#### **32. How to count occurrences?**

#### **33. How to sort an array?**

#### **34. Difference between sort() and argsort()?**

#### **35. How to find index of max/min?**

#### **36. What is where() used for?**

#### **37. What is np.clip()?**

#### **38. What is np.cumsum() and np.cumprod()?**

#### **39. How do you reverse an array?**

#### **40. What is broadcasting rule?**

#### **41. When does broadcasting fail?**

#### **42. How do you transpose a matrix?**

#### **43. What is np.newaxis?**

#### **44. How to expand dimensions?**

#### **45. How to squeeze dimensions?**

#### **46. What is np.meshgrid()?**

#### **47. How to handle NaN values?**

#### **48. Difference between isnan() and isfinite()?**

#### **49. What are universal functions (ufuncs)?**

#### **50. How do ufuncs improve performance?**

## Linear Algebra Level (51–65)

#### **51. What module is used for linear algebra?**

#### **52. How to compute dot product?**

#### **53. Difference between dot and matmul?**

#### **54. How to compute matrix inverse?**

#### **55. When does inverse not exist?**

#### **56. What is determinant?**

#### **57. How to compute determinant?**

#### **58. What are eigenvalues and eigenvectors?**

#### **59. How to compute eigenvalues?**

#### **60. What is SVD?**

#### **61. How to solve linear equations?**

#### **62. What is pseudo-inverse?**

#### **63. What is condition number?**

#### **64. What is Frobenius norm?**

#### **65. How to compute matrix rank?**

## Performance & Memory (66–80)

#### **66. Why is NumPy faster than Python lists?**


#### **67. What is contiguous memory?**


#### **68. What are strides?**


#### **69. How to check memory usage of an array?**


#### **70. What is memory layout (C vs F order)?**


#### **71. What is broadcasting efficiency?**


#### **72. What are views?**


#### **73. What operations return views vs copies?**


#### **74. How to avoid unnecessary copies?**


#### **75. What is vectorization vs loop?**


#### **76. What is np.frombuffer()?**


#### **77. What is np.memmap()?**


#### **78. How to optimize large array computations?**


#### **79. When to use NumPy vs Pandas?**


#### **80. How NumPy interacts with C internally?**


## Advanced Level (81–95)

#### **81. What are structured arrays?**


#### **82. What is masked array?**


#### **83. What is einsum()?**


#### **84. How does einsum() optimize computation?**


#### **85. What is broadcasting with higher dimensions?**


#### **86. What is advanced indexing performance impact?**


#### **87. What is np.lib.stride_tricks?**


#### **88. How does NumPy handle type promotion?**


#### **89. What is object dtype?**


#### **90. What are memory views?**


#### **91. What is np.vectorize() and is it truly vectorized?**


#### **92. What is np.apply_along_axis()?**


#### **93. How to implement custom ufunc?**


#### **94. What is BLAS/LAPACK usage in NumPy?**


#### **95. What are numerical stability issues in NumPy?**


## Expert / Interview Case-Based (96–100)

#### **96. Implement softmax using NumPy (numerically stable).**


#### **97. Implement gradient descent using NumPy.**


#### **98. Normalize dataset column-wise without loops.**
 

#### **99. Find pairwise Euclidean distance matrix efficiently.**


#### **100. Implement PCA using only NumPy.**


## Conceptual Deep Interview Questions

#### **101. Why is NumPy core to libraries like pandas?**


#### **102. How does NumPy support frameworks like TensorFlow and PyTorch?**


#### **103. Why is vectorization critical in ML pipelines?**
