## Basic Level (1-20)

#### **1. What is NumPy and why is it used?**
**NumPy (Numerical Python)** is the foundational library for scientific and numerical computing in Python. It introduces a highly efficient, multi-dimensional array object called `ndarray` and provides a vast collection of mathematical functions to operate on these arrays.

* **Blazing Fast Performance (Vectorization):** Under the hood, NumPy is written in C. It uses **vectorization** to apply operations to entire arrays at once, entirely bypassing Python's slow `for` loops and interpreter overhead.

* **Contiguous Memory Allocation:** Unlike standard Python lists, which are basically arrays of memory pointers pointing to scattered objects, NumPy arrays store elements of the same data type (`dtype`) in single, continuous blocks of memory. This makes fetching and processing data exponentially faster.

* **Broadcasting:** NumPy features a powerful mathematical engine that automatically handles operations between arrays of different shapes and sizes without needing to replicate data in memory.

* **The Ecosystem Foundation:** Almost every major data science and machine learning library in Python (Pandas, SciPy, Scikit-learn, TensorFlow) relies on NumPy arrays as their underlying data structure.

In [12]:
# Importing NumPy Library in Python
import numpy as np

#### **2. What is an ndarray?**
An **`ndarray` (N-dimensional array)** is the central data structure of the NumPy library. It is a fast, flexible container designed to hold large datasets and perform mathematical operations on them efficiently.

**Key Characteristics of an ndarray:**
* **Homogeneous Data:** Every element inside an `ndarray` must be of the exact same data type (e.g., all 32-bit integers, or all 64-bit floats). Because the data type is uniform, NumPy doesn't have to waste time checking the type of every single element before operating on it.

* **Fixed Size:** Unlike standard Python lists which can grow or shrink dynamically, an `ndarray` has a fixed size created at initialization. If you need to change its size (like appending elements), NumPy typically creates a brand new array under the hood.

* **Strided Memory:** Data is stored in a continuous block of memory. The `ndarray` object acts as a "view" that tells Python exactly how to interpret that raw memory (using "strides") to read it as a 1D vector, 2D matrix, or multi-dimensional tensor.

**Must-Know Attributes for Interviews:**
If an interviewer asks how you would inspect a mysterious dataset loaded into a NumPy array, you should immediately mention checking these attributes:

* **`.ndim`**: Returns the number of dimensions (axes).
* **`.shape`**: Returns a tuple showing the size of the array across each dimension (e.g., `(100, 5)` for 100 rows and 5 columns).
* **`.size`**: Returns the total number of elements in the entire array.
* **`.dtype`**: Returns the specific data type of the array's elements (e.g., `float64`, `int32`).

In [13]:
import numpy as np

# Creating an ndarray from a nested Python list (2D Matrix)
data = [[1, 2, 3], 
        [4, 5, 6]]
arr_2d = np.array(data)

print("Target Array:\n", arr_2d)
print("-" * 30)

# Inspecting the crucial attributes (The "Diagnostic Check")
print("Object Type:  ", type(arr_2d))       # <class 'numpy.ndarray'>
print("Dimensions:   ", arr_2d.ndim)        # 2 (since it's a matrix)
print("Shape:        ", arr_2d.shape)       # (2, 3) -> 2 rows, 3 columns
print("Total Size:   ", arr_2d.size)        # 6 elements total
print("Data Type:    ", arr_2d.dtype)       # int32 or int64
print("-" * 30)

# Allocate uninitialized memory
a = np.ndarray(shape=(3, 4)) 
# Overwrite everything using slice assignment [:]
a[:] = [
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]]

print("Using ndarray:\n", a)

Target Array:
 [[1 2 3]
 [4 5 6]]
------------------------------
Object Type:   <class 'numpy.ndarray'>
Dimensions:    2
Shape:         (2, 3)
Total Size:    6
Data Type:     int64
------------------------------
Using ndarray:
 [[ 10.  20.  30.  40.]
 [ 50.  60.  70.  80.]
 [ 90. 100. 110. 120.]]


#### **3. Difference between Python list and NumPy array?**
This is one of the most guaranteed questions in any Python data science interview. Interviewers are looking for you to mention **memory layout**, **homogeneity**, and **vectorization**.

**The Quick Comparison Table**  
| Feature | Python `list` | NumPy `ndarray` |
| --- | --- | --- |
| **Data Types** | **Heterogeneous:** Can mix integers, strings, objects, etc. | **Homogeneous:** All elements must be the exact same data type (`dtype`). |
| **Memory Layout** | **Scattered:** Stores an array of *pointers* to objects scattered across memory. | **Contiguous:** Stores actual data in a single, continuous block of memory. |
| **Performance** | **Slow:** Python must check the type of every single element during iterations. | **Fast:** Uses C-based vectorization; skips element-level type checking. |
| **Math Operations** | **Concatenation:** `+` joins lists together. `*` repeats the list. | **Element-wise:** `+`, `-`, `*` apply the math operation to the actual numbers. |
| **Size** | **Dynamic:** Can easily grow or shrink using `.append()` or `.remove()`. | **Fixed:** Size is locked at creation. Appending usually means creating a brand new array. |

**What to emphasize out loud:**  
*"Because NumPy arrays are strictly typed and contiguous in memory, they can push operations down to highly optimized C-code rather than relying on Python's slow loops. This is called **vectorization**."*

In [14]:
# If an interviewer asks you to demonstrate the difference on a whiteboard or in a live coding pad, 
# show them how the + and * operator behaves differently

import numpy as np
# Python List Behavior
list_a = [1, 2, 3]
list_b = [4, 5, 6]
print("List addition: ", list_a + list_b)
print("List multiplication: ", 2*list_a)  
# Output: [1, 2, 3, 4, 5, 6] (Concatenation)

# NumPy Array Behavior
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
print("Array addition:", arr_a + arr_b)    
print("Array multiplication:", 2*arr_a)    
# Output: [5 7 9] (Element-wise math / Vectorization)

List addition:  [1, 2, 3, 4, 5, 6]
List multiplication:  [1, 2, 3, 1, 2, 3]
Array addition: [5 7 9]
Array multiplication: [2 4 6]


In [15]:
%time np.array([1, 2, 3, 4])
%time list([1, 2, 3, 4])

%time np.array([1.0, 2.0, 3.0, 4.0])
%time list([1.0, 2.0, 3.0, 4.0])

%time np.array([1.0/2, 2.0/2, 3.0/2, 4.0/2])
%time list([1.0/2, 2.0/2, 3.0/2, 4.0/2])

CPU times: user 8 μs, sys: 0 ns, total: 8 μs
Wall time: 10 μs
CPU times: user 2 μs, sys: 1e+03 ns, total: 3 μs
Wall time: 3.1 μs
CPU times: user 4 μs, sys: 0 ns, total: 4 μs
Wall time: 6.2 μs
CPU times: user 1e+03 ns, sys: 1 μs, total: 2 μs
Wall time: 1.91 μs
CPU times: user 2 μs, sys: 0 ns, total: 2 μs
Wall time: 4.05 μs
CPU times: user 1e+03 ns, sys: 0 ns, total: 1e+03 ns
Wall time: 1.67 μs


[0.5, 1.0, 1.5, 2.0]

In [16]:
%time print(np.array([1, 2.5, "Data Science", {1: "toy", 2: "ball"}]))
%time print(list([1, 2.5, "Data Science", {1: "toy", 2: "ball"}]))

[1 2.5 'Data Science' {1: 'toy', 2: 'ball'}]
CPU times: user 83 μs, sys: 15 μs, total: 98 μs
Wall time: 98.2 μs
[1, 2.5, 'Data Science', {1: 'toy', 2: 'ball'}]
CPU times: user 13 μs, sys: 0 ns, total: 13 μs
Wall time: 15.3 μs


#### **4. How do you create a NumPy array?**
For an interview cheat sheet, it is best to categorize array creation methods by their use case. Interviewers often test if you know the most efficient built-in function rather than manually writing loops.

**1. From Existing Data (Lists/Tuples)**  
Use `np.array()` when you already have Python data structures.
* **`np.array(list)`**: Converts a list (or nested list) into a 1D or multi-dimensional array.

**2. Pre-filled Arrays (Shape-Based)**  
Used when you need to allocate an array of a specific shape quickly. You pass a tuple representing the shape, like `(rows, columns)`.
* **`np.zeros(shape)`**: Fills the array with `0.0`. Great for initializing weights in neural networks.
* **`np.ones(shape)`**: Fills the array with `1.0`.
* **`np.full(shape, fill_value)`**: Fills the array with a specific number.

**3. Numerical Sequences**  
Used to generate ranges of numbers automatically.
* **`np.arange(start, stop, step)`**: Works like Python's built-in `range()`, but returns an array. The `stop` value is exclusive.
* **`np.linspace(start, stop, num)`**: Generates exactly `num` evenly spaced points between `start` and `stop` (inclusive). **Interview tip:** Use this when you care about the *exact number of elements* rather than the step size.

**4. Random Data Generation**  
Crucial for creating mock datasets or initializing randomized models.
* **`np.random.rand(d0, d1...)`**: Uniform distribution between 0 and 1.
* **`np.random.randint(low, high, size)`**: Random integers.

In [38]:
import numpy as np

# 1. From existing data
list_data = [10, 20, 30]
arr_from_list = np.array(list_data)
print("arr_from_list: ", arr_from_list)

# 2. Pre-filled arrays (pass a shape tuple)
zeros_matrix = np.zeros((2, 3))       # 2x3 matrix of zeros
full_matrix = np.full((2, 2), 99)     # 2x2 matrix filled with 99
print("full_matrix:\n", full_matrix)
print("zeros_matrix:\n", zeros_matrix)

# 3. Numerical sequences
range_arr = np.arange(0, 10, 2)       # [0, 2, 4, 6, 8]
linear_arr = np.linspace(0, 1, 5)     # [0. , 0.25, 0.5 , 0.75, 1. ]

# 4. Random data
random_ints = np.random.randint(1, 100, size=(3, 3)) # 3x3 matrix of random ints 1-99

print("np.arange output:  ", range_arr)
print("np.linspace output:", linear_arr)
print("Random matrix:\n", random_ints)

arr_from_list:  [10 20 30]
full_matrix:
 [[99 99]
 [99 99]]
zeros_matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]
np.arange output:   [0 2 4 6 8]
np.linspace output: [0.   0.25 0.5  0.75 1.  ]
Random matrix:
 [[61 32 65]
 [16 75 37]
 [43 56  4]]


#### **5. What is the difference between np.array() and np.asarray()?**
This is a classic "gotcha" question that tests your understanding of memory management and copying in Python. The core difference comes down to **whether or not a new copy of the object is created in memory.**

**The Short Answer**  
* **`np.array()`** will create a **copy** of the object by default (though you can change this with the `copy=False` parameter).
* **`np.asarray()`** will **avoid making a copy** whenever possible. If the input is already a NumPy array of the same data type, it simply returns a reference (a view) to the original array.

**Why does this matter for interviews? (The Use Case)**  
If you are writing a machine learning function that takes data as an input, the user might pass a Python list *or* an existing NumPy array.
* If you use `np.array(input_data)`, you might accidentally duplicate a massive 5GB dataset in RAM, crashing your program.
* If you use `np.asarray(input_data)`, lists get safely converted to arrays, but existing arrays pass through instantly without using extra memory.

In [39]:
import numpy as np

# 1. Create an original NumPy array
original = np.array([1, 2, 3])

# 2. Pass it through both functions
arr_copy = np.array(original)
arr_view = np.asarray(original)

# 3. Modify the original array
original[0] = 99

print("Original array: ", original)
# Output: [99, 2, 3]

print("np.array():     ", arr_copy) 
# Output: [1, 2, 3] -> (Unaffected! It made a completely new copy in memory)

print("np.asarray():   ", arr_view) 
# Output: [99, 2, 3] -> (Affected! It just pointed to the original memory block)

Original array:  [99  2  3]
np.array():      [1 2 3]
np.asarray():    [99  2  3]


#### **6. How do you check the shape of an array?**
To check the shape of a NumPy array, you use the **`.shape`** attribute. It returns a tuple of integers representing the number of elements along each dimension (axis) of the array.

**What the interviewer is looking for:**  
They want to ensure you know that `.shape` is an **attribute** (a property of the object), not a method. You should never use parentheses when calling it.
* **Correct:** `arr.shape`
* **Incorrect (will throw an error):** `arr.shape()`

**How to read the shape tuple:**  
* **1D Array (Vector):** `(n,)` where `n` is the number of elements. *Note the trailing comma, which confirms it is a 1D tuple.*
* **2D Array (Matrix):** `(rows, columns)`. For example, `(3, 4)` means 3 rows and 4 columns.
* **3D Array (Tensor):** `(depth, rows, columns)` or `(matrices, rows, columns)`.

In [40]:
import numpy as np

# 1D Array
arr_1d = np.array([10, 20, 30, 40])
print("1D Array shape:", arr_1d.shape)  
# Output: (4,) -> 4 elements in a single dimension

# 2D Matrix
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("2D Matrix shape:", arr_2d.shape) 
# Output: (2, 3) -> 2 rows, 3 columns

# 3D Tensor (e.g., 2 color images, 3 pixels tall, 3 pixels wide)
arr_3d = np.zeros((2, 3, 3))
print("3D Tensor shape:", arr_3d.shape) 
# Output: (2, 3, 3)

1D Array shape: (4,)
2D Matrix shape: (2, 3)
3D Tensor shape: (2, 3, 3)


#### **7. How do you check the datatype of elements?**
To check the datatype of the elements inside a NumPy array, you use the **`.dtype`** attribute.

**What the interviewer is looking for:**  
Interviewers want to see that you understand the difference between inspecting the array object itself versus inspecting the contents of the array.
* **`type(arr)`**: This is a built-in Python function. It will always return `<class 'numpy.ndarray'>` because that is the container's object type.
* **`arr.dtype`**: This is a NumPy attribute. It returns the actual data type of the uniform elements stored *inside* the container (e.g., `int32`, `float64`, `bool`).

**Common Data Types in NumPy**  
* **Integers:** `int8`, `int16`, `int32`, `int64`
* **Floats:** `float16`, `float32`, `float64`
* **Booleans:** `bool_`
* **Strings/Objects:** `object`, `string_`

In [41]:
import numpy as np

# Create an array of integers
arr_int = np.array([1, 2, 3])

# Create an array of floats
arr_float = np.array([1.5, 2.5, 3.5])

# The Interview "Gotcha"
print("Object type:  ", type(arr_int))   # Output: <class 'numpy.ndarray'>
print("Element type: ", arr_int.dtype)   # Output: int32 (or int64 depending on OS)

# Inspecting the float array
print("Float array element type:", arr_float.dtype) # Output: float64

Object type:   <class 'numpy.ndarray'>
Element type:  int64
Float array element type: float64


#### **8. What is dtype in NumPy?**
In NumPy, **`dtype` (data type object)** is an object that describes how the raw bytes in an array's memory block should be interpreted.

While standard Python only has basic types like `int` or `float`, NumPy provides a much finer level of control over data, which is essential for performance and memory management in data science.

**Why `dtype` matters in an interview context:**  
Interviewers want to see that you understand the underlying mechanics of NumPy's speed.
* **The Secret to C-Level Speed:** A standard Python list contains memory pointers pointing to heavy Python objects scattered across RAM. A NumPy array contains a single block of raw bytes. The `dtype` simply tells NumPy, *"Read every 4 bytes in this block as a 32-bit integer."* This allows NumPy to process the data at hardware speeds.
* **Memory Optimization:** In machine learning (like processing millions of images), using a 64-bit float (`float64`) when a 16-bit float (`float16`) would suffice wastes massive amounts of RAM. `dtype` gives you the power to optimize this.

**Common NumPy dtypes:**  
* `int8`, `int16`, `int32`, `int64` (Signed integers)
* `uint8`, `uint16`, `uint32`, `uint64` (Unsigned integers - no negative numbers, often used for image pixels)
* `float16`, `float32`, `float64` (Floating-point numbers)
* `bool_` (Booleans)

In [45]:
# You can explicitly set the `dtype` when you create an array to force NumPy to use a specific memory footprint.
import numpy as np

# 1. Let NumPy infer the dtype (Defaults to int32 or int64)
auto_arr = np.array([1, 2, 3])
print("Inferred dtype: ", auto_arr.dtype)

# 2. Explicitly force a memory-efficient dtype (8-bit integer)
# This uses 4x to 8x less memory than the default!
tiny_arr = np.array([1, 2, 3], dtype=np.int8)
print("Forced dtype:   ", tiny_arr.dtype)

# 3. Force strings to be interpreted as floats
float_arr = np.array(['1.5', '2.6', '3.7'], dtype=np.float32)
print("String to float:", float_arr)

# 4. Force floats to be interpreted as ints
int_arr = np.array([1.5, 2.6, 3.7], dtype=np.int8)
print("Float to int:", int_arr)

Inferred dtype:  int64
Forced dtype:    int8
String to float: [1.5 2.6 3.7]
Float to int: [1 2 3]


#### **9. How to create Zeros array, Ones array, Identity matrix?**

These are fundamental initialization functions in NumPy. Interviewers expect you to know these by heart, as they are constantly used to initialize weights in machine learning models, create masks, or set up linear algebra operations.

**1. Zeros Array: `np.zeros(shape)`**  
Creates an array filled entirely with zeros. You must pass the desired dimensions as a tuple (unless it is just a 1D array, then a single integer works).
* **Default `dtype`:** `float64`. (Interviewers often ask this! Zeros are floats by default, not integers).

**2. Ones Array: `np.ones(shape)`**  
Creates an array filled entirely with ones. Like `np.zeros`, it takes a shape tuple.
* **Pro-tip:** If you need an array filled with 7s, you can do `np.ones(shape) * 7`, though `np.full(shape, 7)` is slightly more efficient.

**3. Identity Matrix: `np.eye(N)` or `np.identity(N)`**  
An identity matrix is a fundamental concept in linear algebra: a square 2D matrix with `1`s on the main diagonal and `0`s everywhere else.
* **`np.eye(N)`:** The most common function. You pass a single integer `N` to create an `N x N` matrix. It is flexible and even allows you to offset the diagonal using the `k` parameter.
* **`np.identity(N)`:** A stricter function that only ever creates square matrices. `np.eye` is generally preferred.

In [46]:
import numpy as np

# 1. Zeros Array
# Pass a single int for 1D, or a tuple for 2D+
zeros_1d = np.zeros(5)
zeros_2d = np.zeros((3, 4)) 
print("Zeros Matrix (3x4):\n", zeros_2d)
print("-" * 20)

# 2. Ones Array
ones_2d = np.ones((2, 2))
print("Ones Matrix (2x2):\n", ones_2d)
print("-" * 20)

# 3. Identity Matrix
# Pass a single integer N to create an N x N square matrix
identity_3x3 = np.eye(3)
print("Identity Matrix (3x3):\n", identity_3x3)

Zeros Matrix (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
--------------------
Ones Matrix (2x2):
 [[1. 1.]
 [1. 1.]]
--------------------
Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### **10. What is the difference between np.arange() and np.linspace()?**
This is a very common interview question. While both functions generate 1D arrays of evenly spaced numbers, they approach the problem from completely different angles.

The short answer is: **`arange` cares about the *step size*, while `linspace` cares about the *number of elements*.**

**The Comparison**  
| Feature | `np.arange(start, stop, step)` | `np.linspace(start, stop, num)` |
| --- | --- | --- |
| **Primary Argument** | The **step size** between each number. | The total **number of points** you want. |
| **Endpoint (stop)** | **Exclusive:** The array stops *before* reaching the stop value. | **Inclusive:** The array includes the stop value (by default). |
| **Best Use Case** | When you know exactly how far apart each number should be (e.g., "count by 2s"). | When you need exactly `N` data points between two boundaries (e.g., graph axes). |
| **Float Handling** | **Dangerous:** Using float steps (like `0.1`) can cause unexpected results due to floating-point precision issues. | **Safe:** Perfectly handles float boundaries and evenly calculates the distance between them. |

**The Interview "Gotcha" (Floating Point Precision)**  
If an interviewer asks, *"How would you create an array of numbers from 0 to 1, stepping by 0.1?"*, you should explain why `linspace` is safer than `arange`.

Because computers struggle to represent fractions like `0.1` perfectly in binary, `np.arange(0, 1, 0.1)` can sometimes include or exclude the final number unpredictably depending on the exact machine architecture. `np.linspace(0, 1, 11)` guarantees exactly 11 points, perfectly spaced.

In [47]:
import numpy as np

# 1. np.arange: "Start at 0, stop BEFORE 10, step by 2"
# We care about the size of the jump.
arange_arr = np.arange(0, 10, 2)
print("arange output:   ", arange_arr) 
# Output: [0, 2, 4, 6, 8] (Notice 10 is excluded)

# 2. np.linspace: "Start at 0, stop AT 10, give me exactly 5 numbers"
# We care about the total number of elements.
linspace_arr = np.linspace(0, 10, 5)
print("linspace output: ", linspace_arr) 
# Output: [ 0.   2.5  5.   7.5 10. ] (Notice 10 is included)

arange output:    [0 2 4 6 8]
linspace output:  [ 0.   2.5  5.   7.5 10. ]


#### **11. How do you reshape an array?**
To reshape a NumPy array, you use the **`.reshape(shape)`** method. This allows you to change the dimensions (like turning a 1D vector into a 2D matrix) without changing the underlying data.

A visual representation of converting a 1D array of 4 elements into a 2x2 matrix:

![Reshape](reshape.png)

**The Golden Rule of Reshaping**  
The total number of elements must remain exactly the same. For example, if you have a 1D array with 12 elements, you can reshape it into `(3, 4)`, `(4, 3)`, or `(2, 6)` because the math multiplies out to 12. If you try to reshape it to `(3, 5)`, NumPy will throw a `ValueError`.

**The `-1` Trick (Interview Must-Know)**  
Interviewers love to test if you know how to use `-1` in reshape.

If you know you want a specific number of columns, but you don't want to calculate how many rows are needed, you can pass `-1` for the unknown dimension. NumPy will automatically calculate the correct size based on the length of the array. This is especially useful in machine learning when you need to convert an unknown number of samples into a single column vector using `.reshape(-1, 1)`.

In [48]:
import numpy as np

# Create a 1D array with 12 elements
arr_1d = np.arange(1, 13) 
print("Original 1D:\n", arr_1d)

# 1. Standard Reshape to 3 rows, 4 columns
arr_2d = arr_1d.reshape((3, 4))
print("\nReshaped to 3x4:\n", arr_2d)

# 2. Reshape to 3D Tensor (2 matrices, 2 rows, 3 columns)
arr_3d = arr_1d.reshape((2, 2, 3))
print("\nReshaped to 2x2x3:\n", arr_3d)

# 3. The -1 Trick: "Give me exactly 1 column, calculate the rows automatically"
column_vector = arr_1d.reshape(-1, 1)
print("\nColumn Vector shape:", column_vector.shape) # Output: (12, 1)

# 4. The -1 Trick: "Give me 4 columns, calculate the rows automatically"
auto_rows = arr_1d.reshape(-1, 4)
print("\nAuto-calculated rows shape:", auto_rows.shape) # Output: (3, 4)

Original 1D:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to 2x2x3:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Column Vector shape: (12, 1)

Auto-calculated rows shape: (3, 4)


#### **12. What is the difference between reshape() and resize()?**

In [26]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a, a.shape)
print(a.reshape(4, 3))

print(np.resize(a, (11, 2)))    # growing or shrinking the array

a.resize((4, 6))
print(a)    # it alters the original array directly

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


#### **13. What is broadcasting?**
- Broadcasting is NumPy's mechanism for performing element-wise operations on arrays of different shapes by virtually "stretching" the smaller array to match the dimensions of the larger one without actually copying memory.

In [27]:
# The scalar 10 is broadcast (stretched) into [10, 10, 10] to match the array's shape
a = np.array([1, 2, 3]) + 10 
print(a) 

[11 12 13]


#### **14. What is vectorization?**
- Vectorization is the practice of replacing explicit Python for loops with NumPy array operations, shifting the mathematical computations to highly optimized, pre-compiled C code for drastically faster performance.

In [28]:
a = np.array([1, 2, 3, 4])
b = 6
# The vectorized approach multiplies the entire array at once, entirely avoiding a slow Python 'for' loop.
print(a*2)
print(a*b)

[2 4 6 8]
[ 6 12 18 24]


#### **15. How to perform element-wise operations?**

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+b)  
print(a*b)  
print(a-5)
print(a**b)
print(np.sqrt(a))
print(np.square(b))
print(np.sin(a))

[5 7 9]
[ 4 10 18]
[-4 -3 -2]
[  1  32 729]
[1.         1.41421356 1.73205081]
[16 25 36]
[0.84147098 0.90929743 0.14112001]


#### **16. What is the difference between * and dot()?**

In [30]:
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])

print(a*b)
print(a.dot(b))

[ 2 12 30]
44


#### **17. How do you concatenate arrays?**

In [31]:
a = np.array([1, 2, 3, 4]).reshape((2, 2))
print(a)
print(np.concatenate([a, a, a], axis=0))
print(np.concatenate([a, a, a], axis=1))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]


#### **18. Difference between vstack() and hstack()?**

In [32]:
a = np.array([1, 2, 3, 4])
print(np.vstack([a, a, a]))
print(np.hstack([a, a, a]))

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[1 2 3 4 1 2 3 4 1 2 3 4]


#### **19. How to generate random numbers?**

In [33]:
a = np.random.randint(1, 10, (2, 3))
print(a)

[[1 6 2]
 [5 1 5]]


#### **20. How do you copy an array? Difference between shallow and deep copy?**

In [34]:
a = np.array([1, 2, 3, 4])
b = a.copy()    # Deep Copy
c = a.view()    # Shallow Copy / c = a
print(a)
print(b)
print(c)

b[0] = 9    # Independently created the array in new memory location
print(a)
print(b)
print(c)

c[0] = 9    # Sharing the same memory location
print(a)
print(b)
print(c)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[9 2 3 4]
[1 2 3 4]
[9 2 3 4]
[9 2 3 4]
[9 2 3 4]


## Intermediate Level (21–50)

#### **21. What is array indexing?**

In [35]:
import numpy as np

a = np.random.randint(0, 9, 3)
b = np.random.randint(0, 9, (3, 3))
c = np.random.randint(0, 9, (2, 3, 3))
print(a)
print(b)
print(c)

print(a[1])
print(b[1], b[[1, 1]])
print(c[1], c[[1, 1]], c[[1, 1, 1]])

[3 2 0]
[[8 1 6]
 [1 8 5]
 [5 2 2]]
[[[2 0 7]
  [2 5 6]
  [8 5 6]]

 [[0 1 4]
  [2 3 3]
  [8 5 1]]]
2
[1 8 5] [[1 8 5]
 [1 8 5]]
[[0 1 4]
 [2 3 3]
 [8 5 1]] [[[0 1 4]
  [2 3 3]
  [8 5 1]]

 [[0 1 4]
  [2 3 3]
  [8 5 1]]] [[[0 1 4]
  [2 3 3]
  [8 5 1]]

 [[0 1 4]
  [2 3 3]
  [8 5 1]]

 [[0 1 4]
  [2 3 3]
  [8 5 1]]]


#### **22. What is slicing?**

In [36]:
import numpy as np

a = np.random.randint(0, 9, 4)
b = np.random.randint(0, 9, (3, 4))
c = np.random.randint(0, 9, (2, 3, 4))
print(a)
print(b)
print(c)

print(a[1:2])
print(b[1:2], )
print(c[:][0:1][1:2])

[7 0 1 4]
[[5 2 8 6]
 [0 0 3 7]
 [1 8 4 7]]
[[[8 6 8 3]
  [3 3 1 0]
  [6 0 3 8]]

 [[7 7 3 2]
  [1 7 0 3]
  [3 8 1 7]]]
[0]
[[0 0 3 7]]
[]


#### **23. What is boolean indexing?**

#### **24. What is fancy indexing?**

#### **25. How to filter values greater than X?**

#### **26. How to replace values conditionally?**

#### **27. What is the difference between ravel() and flatten()?**

#### **28. What is axis in NumPy?**

#### **29. Explain axis=0 vs axis=1.**

#### **30. How do you compute mean, median, std?**

#### **31. How to find unique elements?**

#### **32. How to count occurrences?**

#### **33. How to sort an array?**

#### **34. Difference between sort() and argsort()?**

#### **35. How to find index of max/min?**

#### **36. What is where() used for?**

#### **37. What is np.clip()?**

#### **38. What is np.cumsum() and np.cumprod()?**

#### **39. How do you reverse an array?**

#### **40. What is broadcasting rule?**

#### **41. When does broadcasting fail?**

#### **42. How do you transpose a matrix?**

#### **43. What is np.newaxis?**

#### **44. How to expand dimensions?**

#### **45. How to squeeze dimensions?**

#### **46. What is np.meshgrid()?**

#### **47. How to handle NaN values?**

#### **48. Difference between isnan() and isfinite()?**

#### **49. What are universal functions (ufuncs)?**

#### **50. How do ufuncs improve performance?**

## Linear Algebra Level (51–65)

#### **51. What module is used for linear algebra?**

#### **52. How to compute dot product?**

#### **53. Difference between dot and matmul?**

#### **54. How to compute matrix inverse?**

#### **55. When does inverse not exist?**

#### **56. What is determinant?**

#### **57. How to compute determinant?**

#### **58. What are eigenvalues and eigenvectors?**

#### **59. How to compute eigenvalues?**

#### **60. What is SVD?**

#### **61. How to solve linear equations?**

#### **62. What is pseudo-inverse?**

#### **63. What is condition number?**

#### **64. What is Frobenius norm?**

#### **65. How to compute matrix rank?**

## Performance & Memory (66–80)

#### **66. Why is NumPy faster than Python lists?**


#### **67. What is contiguous memory?**


#### **68. What are strides?**


#### **69. How to check memory usage of an array?**


#### **70. What is memory layout (C vs F order)?**


#### **71. What is broadcasting efficiency?**


#### **72. What are views?**


#### **73. What operations return views vs copies?**


#### **74. How to avoid unnecessary copies?**


#### **75. What is vectorization vs loop?**


#### **76. What is np.frombuffer()?**


#### **77. What is np.memmap()?**


#### **78. How to optimize large array computations?**


#### **79. When to use NumPy vs Pandas?**


#### **80. How NumPy interacts with C internally?**


## Advanced Level (81–95)

#### **81. What are structured arrays?**


#### **82. What is masked array?**


#### **83. What is einsum()?**


#### **84. How does einsum() optimize computation?**


#### **85. What is broadcasting with higher dimensions?**


#### **86. What is advanced indexing performance impact?**


#### **87. What is np.lib.stride_tricks?**


#### **88. How does NumPy handle type promotion?**


#### **89. What is object dtype?**


#### **90. What are memory views?**


#### **91. What is np.vectorize() and is it truly vectorized?**


#### **92. What is np.apply_along_axis()?**


#### **93. How to implement custom ufunc?**


#### **94. What is BLAS/LAPACK usage in NumPy?**


#### **95. What are numerical stability issues in NumPy?**


## Expert / Interview Case-Based (96–100)

#### **96. Implement softmax using NumPy (numerically stable).**


#### **97. Implement gradient descent using NumPy.**


#### **98. Normalize dataset column-wise without loops.**
 

#### **99. Find pairwise Euclidean distance matrix efficiently.**


#### **100. Implement PCA using only NumPy.**


## Conceptual Deep Interview Questions

#### **101. Why is NumPy core to libraries like pandas?**


#### **102. How does NumPy support frameworks like TensorFlow and PyTorch?**


#### **103. Why is vectorization critical in ML pipelines?**
