## Basic Level (1-20)

#### 1. What is NumPy and why is it used?
- NumPy or "Numerical Python" is a python library used for numerical calculations in python. And NumPy is very fast in terms of numerical calculations. We can use NumPy in python as mentioned below.

In [1]:
import numpy as np

#### 2. What is an ndarray?
- Array in NumPy is an one dimensional array. ndarray is n dimentional array in NumPy.

In [26]:
a = np.ndarray(shape=(3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 3. Difference between Python list and NumPy array?
- The main difference between Python list and NumPy array is mentioned below in terms of speed(NumPy Array is Faster) and element datatypes(NumPy array can only take numbers)

In [12]:
%time np.array([1, 2, 3, 4])
%time list([1, 2, 3, 4])

%time np.array([1.0, 2.0, 3.0, 4.0])
%time list([1.0, 2.0, 3.0, 4.0])

%time np.array([1.0/2, 2.0/2, 3.0/2, 4.0/2])
%time list([1.0/2, 2.0/2, 3.0/2, 4.0/2])

CPU times: user 21 μs, sys: 0 ns, total: 21 μs
Wall time: 21.9 μs
CPU times: user 2 μs, sys: 1e+03 ns, total: 3 μs
Wall time: 4.05 μs
CPU times: user 7 μs, sys: 0 ns, total: 7 μs
Wall time: 8.11 μs
CPU times: user 1 μs, sys: 0 ns, total: 1 μs
Wall time: 1.67 μs
CPU times: user 3 μs, sys: 1 μs, total: 4 μs
Wall time: 3.81 μs
CPU times: user 1 μs, sys: 0 ns, total: 1 μs
Wall time: 3.1 μs


[0.5, 1.0, 1.5, 2.0]

In [21]:
%time print(np.array([1, 2.5, "Data Science", {1: "toy", 2: "ball"}]))
%time print(list([1, 2.5, "Data Science", {1: "toy", 2: "ball"}]))

[1 2.5 'Data Science' {1: 'toy', 2: 'ball'}]
CPU times: user 139 μs, sys: 6 μs, total: 145 μs
Wall time: 142 μs
[1, 2.5, 'Data Science', {1: 'toy', 2: 'ball'}]
CPU times: user 18 μs, sys: 1 μs, total: 19 μs
Wall time: 20.3 μs


#### 4. How do you create a NumPy array?

In [22]:
import numpy as np
a = np.array([1, 2, 5, 4.3, 33.0])
print(a, type(a))

[ 1.   2.   5.   4.3 33. ] <class 'numpy.ndarray'>


#### 5. What is the difference between np.array() and np.asarray()?

In [ ]:
import numpy as np

original_array = np.array([1, 3, 5, 7])
new_array = np.array(original_array) # Always makes a copy in the memory
print(original_array)
print(new_array)

original_array[0] = 99
print(original_array)
print(new_array)

[1 3 5 7]
[1 3 5 7]
[99  3  5  7]
[1 3 5 7]


In [ ]:
import numpy as np

original_array = np.array([1, 3, 5, 7])
new_array = np.asarray(original_array) # Uses the same memory location as the original_array(the datatype should be same)
print(original_array)
print(new_array)

original_array[0] = 99
print(original_array)
print(new_array)

[1 3 5 7]
[1 3 5 7]
[99  3  5  7]
[99  3  5  7]


#### 6. How do you check the shape of an array?

In [24]:
a = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
print(a)
print(a.shape)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
(3, 3)


#### 7. How do you check the datatype of elements?

In [32]:
a = np.ndarray((2,3))
print(a)
print(type(a))

b = {"a": 100, "b": 200}
print(b)
print(type(b))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
{'a': 100, 'b': 200}
<class 'dict'>


## Intermediate Level (21–50)

## Linear Algebra Level (51–65)

## Performance & Memory (66–80)

## Advanced Level (81–95)

## Expert / Interview Case-Based (96–100)